#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'../..');const specs=JSON.parse(fs.readFileSync(path.join(ROOT,'data/page_families/velocity_page_specs.json'),'utf8')).pages||[];const editorial=JSON.parse(fs.readFileSync(path.join(ROOT,'content/_live/pages.json'),'utf8')).pages||[];const automaticPages=editorial.filter(p=>p.velocity_only_program==='AUTOMATIC_PUBLIC_SIGNAL_RELEASE');const errors=[],warnings=[];const counts=[];const automaticCounts=[];
function text(html){return html.replace(/<(script|style)[\s\S]*?<\/\1>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[a-z0-9#]+;/gi,' ').replace(/\s+/g,' ').trim();}
function words(s){return String(s||'').split(/\s+/).filter(Boolean).length;}
for(const p of specs.filter(x=>x.state)){
 const file=path.join(ROOT,p.slug.replace(/^\//,''),'index.html');if(!fs.existsSync(file)){errors.push(`${p.slug}:rendered-file-missing`);continue;}const html=fs.readFileSync(file,'utf8');const wc=words(text(html));counts.push(wc);if(wc<300)errors.push(`${p.slug}:rendered_unusably_thin:${wc}`);else if(wc<700)warnings.push(`${p.slug}:rendered_depth_advisory:${wc}`);if(!html.includes('data-state-authority="true"'))errors.push(`${p.slug}:authority-card-missing`);if(!html.includes(p.state_authority?.authority_url||'__missing__'))errors.push(`${p.slug}:authority-url-missing`);const faqCount=(html.match(/class=\"acc-item\"/gi)||[]).length+(html.match(/<details\b/gi)||[]).length;if(faqCount<3)errors.push(`${p.slug}:insufficient_visible_decision_sections:${faqCount}`);else if(faqCount<5)warnings.push(`${p.slug}:visible_section_count_advisory:${faqCount}`);const ctaCount=(html.match(/Find a Provider/gi)||[]).length;if(ctaCount<1)errors.push(`${p.slug}:provider_cta_missing`);else if(ctaCount<2)warnings.push(`${p.slug}:provider_cta_depth_advisory`);if(/usa\.gov\/states\//i.test(html))errors.push(`${p.slug}:generic-usagov-source`);if(/\b(TODO|TBD|placeholder|lorem ipsum)\b/i.test(text(html)))errors.push(`${p.slug}:placeholder-copy`);
}
for(const p of automaticPages){
 const file=path.join(ROOT,p.slug.replace(/^\//,''),'index.html');if(!fs.existsSync(file)){errors.push(`${p.slug}:automatic_rendered_file_missing`);continue;}const html=fs.readFileSync(file,'utf8');const wc=words(text(html));automaticCounts.push(wc);if(wc<250)errors.push(`${p.slug}:automatic_rendered_unusably_thin:${wc}`);else if(wc<500)warnings.push(`${p.slug}:automatic_rendered_depth_advisory:${wc}`);const faqCount=(html.match(/class="acc-item"/gi)||[]).length+(html.match(/<details\b/gi)||[]).length;if(faqCount<3)errors.push(`${p.slug}:automatic_insufficient_visible_sections:${faqCount}`);else if(faqCount<5)warnings.push(`${p.slug}:automatic_visible_section_count_advisory:${faqCount}`);const autoCtaCount=(html.match(/Find a Provider/gi)||[]).length;if(autoCtaCount<1)errors.push(`${p.slug}:automatic_provider_cta_missing`);else if(autoCtaCount<2)warnings.push(`${p.slug}:automatic_provider_cta_depth_advisory`);for(const url of p.source_urls||[])if(!html.includes(url))errors.push(`${p.slug}:automatic_source_url_missing:${url}`);if(/\b(TODO|TBD|placeholder|lorem ipsum)\b/i.test(text(html)))errors.push(`${p.slug}:automatic_placeholder_copy`);
}
const report={validator:'rendered-programmatic-substance',status:errors.length?'FAIL':'PASS',state_pages:counts.length,minimum_rendered_words:counts.length?Math.min(...counts):0,maximum_rendered_words:counts.length?Math.max(...counts):0,average_rendered_words:counts.length?Math.round(counts.reduce((a,b)=>a+b,0)/counts.length):0,automatic_pages:automaticCounts.length,automatic_minimum_rendered_words:automaticCounts.length?Math.min(...automaticCounts):0,automatic_average_rendered_words:automaticCounts.length?Math.round(automaticCounts.reduce((a,b)=>a+b,0)/automaticCounts.length):0,error_count:errors.length,warning_count:warnings.length,errors,warnings,checked_at:process.env.SOURCE_DATE||'2026-06-19'};fs.mkdirSync(path.join(ROOT,'artifacts/validation'),{recursive:true});fs.writeFileSync(path.join(ROOT,'artifacts/validation/rendered-programmatic-substance.json'),JSON.stringify(report,null,2)+'\n');if(errors.length){console.error(errors.slice(0,100).join('\n'));process.exit(1);}console.log(`RENDERED PROGRAMMATIC SUBSTANCE PASS: ${counts.length} state pages (min ${report.minimum_rendered_words}, avg ${report.average_rendered_words}); ${automaticCounts.length} automatic pages (min ${report.automatic_minimum_rendered_words}, avg ${report.automatic_average_rendered_words}).`);
