'use strict';

function makeConfig(shortTitle, shortSummary, checklistTitle, checklistIntro, checklistItems, frameworkTitle, frameworkBullets, modules){
  return { shortTitle, shortSummary, checklistTitle, checklistIntro, checklistItems, frameworkTitle, frameworkBullets, modules };
}

function m(title, match, summary, checklist = [], red_flags = []){
  return { title, match, summary, checklist, red_flags };
}

const CONFIG = {
  '/personal-injury/best-top-near-me/': makeConfig(
    'Quick answer',
    'People usually choose a personal injury lawyer by checking case-type fit, fee structure, trial readiness, and who will actually run the case. Use the checklist first, then verify local details on the official guide.',
    'How to choose a personal injury lawyer',
    'Most people make a better choice when they compare a few non-negotiables before talking about “best” or “top rated.”',
    ['Confirm the lawyer handles your accident type', 'Get the contingency fee and case costs in writing', 'Ask who will actually run the file day to day', 'Compare trial readiness, not just ad visibility', 'Talk to 2–3 firms before signing'],
    'What usually drives the decision',
    ['Case-type fit matters more than slogans.', 'Fee structure and costs can change your net payout.', 'Trial leverage and communication quality usually matter more than review volume.'],
    [
      m('Start with case-type fit and plaintiff-side focus', ['truck','motorcycle','wrongful','slip','serious','rear-end','hit-and-run','rideshare','uninsured','pedestrian','bicycle','accident type','local personal injury lawyer'], 'Start by confirming the lawyer is plaintiff-side and regularly handles your accident type. A general litigator or intake-heavy ad firm is not the same as someone who routinely handles the exact claim pattern you have.', ['Ask how often they handle your accident type', 'Confirm they represent injured plaintiffs, not insurers', 'Ask what makes your case type different operationally'], ['They answer only with marketing slogans', 'They cannot explain case-type differences']),
      m('Compare firms using a real shortlist, not “best” claims', ['best','top rated','most experienced','real decision checklist','slogans','shortlist'], 'Treat “best” as a filtering question, not a verdict. The useful comparison is usually lawyer type, communication style, fee clarity, and whether the firm can explain your next steps without pressuring you to sign immediately.', ['Compare 2–3 firms side by side', 'Use the same questions in every consultation', 'Write down what each firm says about timing and next steps'], ['They rely on rankings instead of specifics', 'They pressure you to sign on the first call']),
      m('Understand contingency fees and case costs before signing', ['contingency','fee','fees','coverage','included'], 'The important fee questions are not just the percentage. Ask how costs are handled, whether the fee changes if a case is filed or tried, and what comes out before or after the attorney fee is calculated.', ['Ask for the fee agreement in writing', 'Ask whether costs are deducted before or after the fee', 'Ask whether the percentage changes if the case escalates'], ['They will not explain costs in writing', 'They dodge questions about deductions or liens']),
      m('Use the consultation to see who will actually handle the case', ['free consultation','who handles','communication'], 'A free consultation is useful when it tells you who will manage the file, how updates work, and whether the firm can explain your likely process without overpromising outcomes.', ['Ask who your day-to-day contact is', 'Ask how often updates happen', 'Ask whether the lead lawyer will stay involved after intake'], ['The signer disappears after intake', 'They cannot explain how communication works']),
      m('Check reviews and case results without getting fooled', ['reviews','marketing','settlement claims','judge settlement claims'], 'Reviews and case results can help, but only when you read them as context. Look for detail, consistency, and whether the firm can explain the kinds of cases behind any large numbers it advertises.', ['Look for specific review detail, not only volume', 'Ask what kinds of cases produced the quoted results', 'Compare whether they explain both settlements and litigation'], ['Only vague “millions recovered” claims', 'Reviews feel generic or heavily scripted']),
      m('Trial readiness and local fit matter when the claim gets harder', ['local','state','trial','narrow an injury-lawyer shortlist'], 'When liability, damages, or negotiation become contested, local practice patterns and trial readiness can matter more than broad ad visibility. A firm should be able to explain why local experience changes strategy.', ['Ask how local judges or insurers affect strategy', 'Ask what changes if the case must be filed', 'Ask whether they regularly work in your county or region'], ['They say local rules never matter', 'They cannot explain what changes if a case gets harder'])
    ]
  ),
  '/personal-injury/trust-red-flags/': makeConfig(
    'Quick answer',
    'Trust usually comes down to licensing, written fees, communication quality, and whether the firm explains risk without pressure. Red flags usually show up early if you know what to ask.',
    'How to pressure-test a personal injury firm',
    'Use this page to spot avoidable mistakes before you sign or share too much detail.',
    ['Verify license and discipline history', 'Ask how updates and case handling work', 'Require fees and costs in writing', 'Do not sign under pressure', 'Compare more than one firm if anything feels off'],
    'What trust usually means here',
    ['Legit firms explain fees and process clearly.', 'Pressure, promises, and silence are stronger signals than branding.', 'You should be able to leave a consultation understanding the next step.'],
    [
      m('Verify the lawyer is licensed, active, and in good standing', ['legit','license','discipline'], 'Start by checking whether the lawyer is licensed in your state and whether any discipline history changes your comfort level. A trustworthy firm should not treat this as a hostile question.', ['Check the state bar listing', 'Ask for the full attorney name who would represent you', 'Check whether discipline history needs explanation'], ['They resist giving the attorney name', 'They dismiss bar-status questions']),
      m('Pressure and payout promises are major warning signs', ['big payout','settle fast','pressures me to sign today','promises'], 'A firm that promises a big result or pressures you to sign immediately is usually optimizing intake, not fit. Good firms explain uncertainty and give you time to compare.', ['Ask for the realistic range of outcomes', 'Notice whether they explain uncertainty', 'Walk away from same-call pressure'], ['Guaranteed results', 'Artificial urgency to sign today']),
      m('Written fee terms and consent boundaries matter', ['bad fee agreement','fees in writing','settle without my permission'], 'You should know who controls settlement decisions, how fees work, and how costs are handled before you sign. These are trust issues, not paperwork details.', ['Ask who must approve settlement', 'Ask how costs are deducted', 'Ask for the fee agreement before signing'], ['They refuse to put terms in writing', 'They are vague about who controls settlement decisions']),
      m('Communication problems usually get worse, not better', ['won’t call me back','updates','how often should i get updates'], 'If communication already feels sloppy during intake, assume it will feel worse once the file is signed. Clear update expectations are part of basic trust.', ['Ask how often you should expect updates', 'Ask who answers urgent questions', 'Ask how to reach the person actually running the file'], ['Slow or evasive intake responses', 'No clear contact person']),
      m('Protect yourself when comparing referrals, reviews, and multiple firms', ['referrals','reviews','compare 2–3 firms','more than one lawyer','local lawyer'], 'Reviews, referrals, and local familiarity can help, but none of them replace direct comparison. It is normal to talk to multiple firms before choosing.', ['Use the same questions with every firm', 'Compare what each firm says about process and fees', 'Treat reviews as one signal, not the whole answer'], ['They tell you not to compare firms', 'They rely only on referral reputation']),
      m('Protect the claim while you are still deciding', ['sharing details','record calls','post about my accident online'], 'Before you choose counsel, avoid careless disclosures that can complicate the claim. Intake convenience should not push you into sharing more than necessary or posting about the incident publicly.', ['Be careful with recorded statements', 'Avoid posting claim details online', 'Ask before sharing sensitive documents broadly'], ['They encourage risky public or insurer disclosures', 'They do not explain basic claim-protection habits'])
    ]
  ),
  '/personal-injury/cost-fees/': makeConfig(
    'Quick answer',
    'Personal injury fees are usually contingency-based, but the real comparison is the percentage, case costs, liens, and how the final payout is calculated. Small contract details can materially change what you keep.',
    'How to compare injury-lawyer costs',
    'Use the cost page to understand what you may pay, what comes out of the settlement, and what to ask before signing.',
    ['Get the contingency percentage in writing', 'Ask how case costs are advanced and repaid', 'Ask what happens if the case is lost or switched', 'Ask how liens and medical bills affect the payout', 'Do not compare fee percentages without comparing deductions'],
    'What usually changes your net recovery',
    ['The fee percentage is only one line item.', 'Case costs, liens, and timing affect what you actually keep.', 'Cheap intake can still become expensive if the contract is vague.'],
    [
      m('Understand the contingency fee before you compare percentages', ['cost','up front','percentage','free consultation','contingency'], 'Most people do not pay up front for a personal injury lawyer, but you still need to understand the fee percentage, when it changes, and what work it is meant to cover.', ['Ask whether the percentage changes if a lawsuit is filed', 'Ask whether the consultation is truly free', 'Ask whether you owe anything if the case does not recover money'], ['They quote only a percentage and nothing else', 'They avoid explaining the fee stages']),
      m('Case costs and records can change the real total', ['hidden fees','case costs','records and experts','medical lien'], 'Case costs can include records, filing fees, experts, and other expenses. The important question is how those costs are advanced and whether they come out before or after the attorney fee is calculated.', ['Ask for examples of typical case costs', 'Ask how costs are repaid', 'Ask whether major expenses require discussion first'], ['No explanation of costs beyond “it depends”', 'No written language about reimbursement order']),
      m('Payout timing, liens, and reimbursements affect what you keep', ['paid out','get paid','health insurance','medical bills','liens'], 'The settlement amount is not the same as the amount you take home. Medical liens, health-insurance reimbursement, and unresolved bills can materially change the final payout.', ['Ask who explains lien resolution', 'Ask when funds are typically disbursed', 'Ask what can delay the final check'], ['They cannot explain why settlement money can be delayed', 'They speak only about gross recovery and never net payout']),
      m('Use settlement offers and case value estimates carefully', ['first offer','fair','estimate case value','small','soft tissue'], 'Case value estimates are only useful if the firm explains what drives them. Early offers, minor vehicle damage, or soft-tissue disputes can change negotiation leverage, but they do not automatically eliminate the claim.', ['Ask what facts are helping or hurting the value', 'Ask how medical treatment affects timing and leverage', 'Ask what would make an offer too early to evaluate'], ['They guarantee value before reviewing records', 'They dismiss legitimate soft-tissue or low-damage questions']),
      m('Switching firms and self-handling questions deserve direct answers', ['switch lawyers','paying twice','cancel','cheaper to handle it myself'], 'If you are comparing lawyers or thinking about switching, ask directly how fee sharing, file transfer, or cancellation works. Cost comparisons should include the risk of handling a claim without counsel.', ['Ask whether switching creates additional fee exposure', 'Ask how cancellation is handled', 'Ask what work you would realistically do yourself if you did not hire counsel'], ['They refuse to explain switch/cancel mechanics', 'They give only dismissive answers about self-representation'])
    ]
  ),
  '/personal-injury/situations/': makeConfig(
    'Quick answer',
    'Common injury situations still come back to the same core questions: what happened, who may be responsible, what evidence exists, and what would change the next step. The page works best as a triage guide, not as a promise of outcome.',
    'How to use situation-specific injury questions',
    'Use the situation page to figure out what changes the next step when the facts are messy or the injury pattern is unusual.',
    ['Clarify what happened and when', 'Write down the evidence you already have', 'Identify what urgency or deadline might apply', 'Ask what facts would change the claim strategy', 'Use the local guide before acting on assumptions'],
    'What usually changes by situation',
    ['Liability facts matter more than labels.', 'Documentation and timing affect leverage quickly.', 'The right next question depends on what is still unknown.'],
    [
      m('Start with what happened, what injuries exist, and what proof you have', ['situation','what if','common situations','rear','slip','pedestrian','rideshare'], 'Before comparing legal strategy, clarify the incident facts, injury pattern, and available proof. Many “situation” questions are really documentation and liability questions in disguise.', ['Write down what happened in plain language', 'List what records, photos, or witnesses exist', 'Identify what is still missing'], ['You cannot explain the basic fact pattern', 'You rely only on what the adjuster told you']),
      m('Identify what changes liability or insurance handling', ['fault','insurance','coverage','uninsured','rideshare'], 'The next step often depends on who may be responsible and which insurance layers may apply. That is why apparently similar accidents can move differently.', ['Ask what facts change the liability picture', 'Ask which insurer is actually involved', 'Ask whether any deadlines or notice rules apply'], ['No one explains which insurer or policy matters', 'You assume fault rules are the same everywhere']),
      m('Use medical treatment and timing to understand urgency', ['medical','treatment','pain','delay'], 'Treatment timing and follow-through can affect both health recovery and claim credibility. Situation pages should help you identify when delay creates a practical problem.', ['Ask what treatment steps matter now', 'Ask what records you should preserve', 'Ask how delay could affect the claim'], ['You are told treatment timing never matters', 'You are encouraged to ignore documentation']),
      m('Use the local guide when the facts stop being generic', ['state','local','next step'], 'Once the question becomes local, practical, or insurer-specific, move to the canonical local guide. Situation pages should orient you, not replace location-specific next steps.', ['Use this page to frame the question', 'Move to the official local guide when you need local routing', 'Keep notes from this triage step'], ['You stay on summary pages instead of moving to local workflow'])
    ]
  ),
  '/dentistry/best-top-near-me/': makeConfig(
    'Quick answer',
    'People usually choose a dentist by confirming provider type, treatment-plan clarity, written pricing, and whether the office feels trustworthy under pressure. “Top rated” matters less than fit, explanation quality, and whether the next step is clear.',
    'How to choose a dentist without guessing',
    'Use a shortlist, compare the same questions at each office, and do not confuse marketing polish with a good clinical fit.',
    ['Confirm whether you need a general dentist or a specialist', 'Ask for a written treatment plan and estimate', 'Compare how clearly options and alternatives are explained', 'Check how urgent care, follow-up, or sedation are handled', 'Do not choose on reviews alone'],
    'What usually drives a good dental choice',
    ['The right provider type matters first.', 'A written treatment plan beats a vague verbal pitch.', 'Pricing and trust issues usually show up early if you ask directly.'],
    [
      m('Start with the right provider type and treatment fit', ['credentials','pediatric','family','implant','endodontic','restorative','braces','orthodontic','aligner','specialist'], 'The first question is whether you need a general dentist or a specialist. A good office should explain that distinction clearly before you commit to treatment.', ['Ask whether your case belongs with a general dentist or specialist', 'Ask how often they handle your treatment type', 'Ask whether they would refer out anything important'], ['They claim to do everything equally well', 'They avoid explaining specialist limits']),
      m('Use treatment-plan clarity to compare offices', ['compare local dental offices','what makes a dentist good','compare dentists','private practice','chain dental office'], 'A strong office can explain options, alternatives, and why one plan is being recommended. Good comparison usually sounds like a treatment conversation, not a sales script.', ['Ask what alternatives exist', 'Ask what happens if you wait', 'Ask for the plan in writing'], ['No written treatment plan', 'Heavy pressure to say yes immediately']),
      m('Price, insurance, and financing should be understandable before booking', ['coverage','fee structure','self-pay','pricing'], 'You do not need every exact number on the first call, but you should understand whether the office gives written estimates, how insurance is handled, and whether financing changes the total.', ['Ask for a written estimate', 'Ask whether they are in network or only submit claims', 'Ask whether financing adds fees or conditions'], ['They refuse to discuss estimates', 'The office is vague about insurance and financing']),
      m('Urgent, same-day, or anxiety-sensitive care needs a different comparison lens', ['urgent','same-day','sedation','anxiety','tooth pain','broken tooth','gum symptoms'], 'Emergency care, sedation, and anxiety-friendly dentistry should be evaluated differently from routine cleanings. Availability matters, but so do safety, communication, and whether follow-up is clear.', ['Ask what can be handled same day', 'Ask who manages sedation decisions', 'Ask what aftercare or follow-up looks like'], ['They promise urgent help without triage questions', 'They cannot explain sedation or aftercare clearly']),
      m('Read reviews and ratings as context, not proof', ['top rated','reviews'], 'Reviews can help when they reveal communication quality, follow-up, and consistency across visits. Ratings alone are not enough to choose a provider.', ['Look for detail about communication and outcomes', 'Compare whether complaints repeat the same theme', 'Use reviews to build questions, not make the whole decision'], ['Only generic praise with no specifics', 'The office leans on ratings and avoids direct questions'])
    ]
  ),
  '/dentistry/anxiety-trust/': makeConfig(
    'Quick answer',
    'Anxiety-friendly and trustworthy dental care usually feels calmer, clearer, and less sales-driven from the first interaction. The right office should explain sedation, pacing, alternatives, and follow-up without pushing you past your comfort level.',
    'How to pressure-test dental trust and anxiety fit',
    'Use this page to compare how offices handle communication, comfort, and informed choice before you say yes to treatment.',
    ['Ask how anxious or pain-sensitive patients are handled', 'Ask what sedation options are and who manages them', 'Ask whether treatment can be staged or paced', 'Ask what alternatives exist if you are uncomfortable', 'Notice whether the office responds with calm explanation or pressure'],
    'What usually builds trust here',
    ['Trust shows up in explanation quality.', 'Sedation and comfort conversations should be clear, not casual.', 'Pressure and vague answers usually get worse after you book.'],
    [
      m('Trust starts with clear explanation and alternatives', ['trust','questions','good dentist','reviews'], 'A trustworthy office explains the plan, the alternatives, and what happens if you wait. Anxiety gets worse when the office acts like questions are a problem.', ['Ask what alternatives exist', 'Ask what happens if you wait', 'Ask what part of the plan is optional vs urgent'], ['They dismiss questions as overthinking', 'They refuse to discuss alternatives']),
      m('Sedation and anxiety support should be explicit, not implied', ['sedation','anxiety'], 'If you need sedation or extra anxiety support, ask exactly what is offered, who decides, and how safety and follow-up work. You should not have to infer this from marketing language.', ['Ask which sedation options are available', 'Ask who monitors and explains sedation risk', 'Ask whether the treatment can be staged in smaller steps'], ['They promise sedation without details', 'No one can explain how anxious patients are supported']),
      m('Second opinions and treatment pressure reveal a lot', ['compare','second opinion','upsell'], 'When an office pushes a costly treatment without explaining options, a second opinion is often the right move. Trust improves when the office can explain why their recommendation makes sense.', ['Ask whether a second opinion would change anything', 'Ask what information would help you compare', 'Ask which parts of the plan are the highest priority'], ['Immediate pressure to approve expensive work', 'No explanation for why alternatives are not suitable']),
      m('Reviews and follow-up communication should make the office easier to predict', ['reviews','communication','follow up'], 'Read reviews for communication, billing clarity, and how patients felt after treatment. Predictability matters as much as bedside manner.', ['Look for repeat themes in communication or billing', 'Ask who answers post-visit questions', 'Ask how urgent concerns are handled after treatment'], ['Follow-up process is vague', 'Billing complaints repeat and go unanswered'])
    ]
  ),
  '/dentistry/cost-insurance/': makeConfig(
    'Quick answer',
    'Dental costs vary because treatment scope, insurance rules, materials, urgency, and follow-up are not the same from office to office. The safest comparison is a written estimate plus a clear explanation of what could change the total.',
    'How to compare dental cost before you book',
    'Use the cost page to compare written estimates, insurance handling, and common surprise-charge traps.',
    ['Ask for a written estimate before treatment', 'Ask what might change the total after exam or imaging', 'Ask whether the office is in network, out of network, or only files claims', 'Ask how financing or payment plans affect the real total', 'Compare quotes only after you confirm what is included'],
    'What usually changes the dental price',
    ['The treatment plan drives the number first.', 'Insurance status does not tell you the whole total.', 'Cheap quotes become expensive when follow-up, materials, or add-ons are vague.'],
    [
      m('Start with the written estimate and what is included', ['pricing','written estimate','surprise charges'], 'A useful estimate should tell you what the office believes is included now and what could change once the exam, x-rays, or treatment plan are finalized.', ['Ask what the estimate includes', 'Ask what could increase the total', 'Ask whether follow-up visits are billed separately'], ['No written estimate', 'They say the total will be explained later']),
      m('Insurance, Medicaid, and network status need plain-English confirmation', ['insurance','medicaid','in-network','out-of-network'], 'Do not assume “we take your insurance” means the same thing as being in network. Clarify whether the office is contracted, files claims, or expects you to manage reimbursement yourself.', ['Ask whether the office is truly in network', 'Ask whether they accept Medicaid for your exact need', 'Ask what insurance does not cover'], ['They answer insurance questions vaguely', 'They cannot explain what you will actually owe']),
      m('Procedure prices vary because the treatment details vary', ['cleaning','fillings','root canal','crown','implants','dentures','extraction','varies'], 'Procedure labels are not interchangeable products. Cost differences often reflect complexity, materials, staging, imaging, and who is doing the work.', ['Ask what version of the procedure is being quoted', 'Ask whether imaging or specialist care is included', 'Ask what happens if the treatment plan changes'], ['They quote a low starting price with no scope details', 'They avoid explaining why their quote differs']),
      m('Financing, discount plans, and low-cost options deserve careful scrutiny', ['financing','discount plans','dental school','low-cost clinics'], 'Payment plans and discount offers can help, but only if you understand fees, limitations, and whether the office is still a good clinical fit for your problem.', ['Ask whether financing adds fees or obligations', 'Ask whether low-cost care changes provider type or follow-up', 'Ask whether a discount plan affects your treatment choices'], ['The offer is all about payment and not about care fit', 'No one explains the tradeoffs of the cheaper option']),
      m('Emergency pricing should be compared differently from routine care', ['emergency dental cost'], 'Emergency visits are often triage-first, which means the initial price may not be the final treatment total. Ask what is being handled today versus what may come next.', ['Ask what today’s fee covers', 'Ask what follow-up treatment could cost', 'Ask what happens if pain or infection requires another visit'], ['They imply one visit solves everything without qualification'])
    ]
  ),
  '/dentistry/emergency-open-now/': makeConfig(
    'Quick answer',
    'Urgent dental care is usually about triage, pain control, infection risk, and whether the office can actually handle the problem the same day. Speed matters, but clarity matters more than an “open now” headline.',
    'How to compare emergency dental options',
    'Use this page to decide what needs immediate care, what you should ask before going, and what “same-day” really means.',
    ['Confirm whether your problem needs same-day dental care or ER care', 'Ask what can realistically be handled in one visit', 'Ask what records, x-rays, or medications you should bring', 'Ask what the first-visit cost covers', 'Ask what happens if follow-up is needed'],
    'What usually matters in urgent dental care',
    ['Triage quality matters more than urgency marketing.', 'Same-day availability is only useful if the office can explain the next step.', 'Pain, swelling, trauma, and follow-up all change the best choice.'],
    [
      m('Know what is urgent and what is not', ['urgent','same-day','open now','tooth pain','broken tooth','gum symptoms'], 'Emergency dental decisions start with triage. The key question is whether the office can tell you what needs immediate attention and what can safely wait for a planned visit.', ['Ask whether your symptoms require same-day care', 'Ask whether they can handle trauma, infection, or swelling', 'Ask whether an ER is more appropriate in your situation'], ['They promise same-day care without asking about symptoms', 'They cannot explain when ER care is safer']),
      m('Ask what can actually be done in the first visit', ['availability','what to expect'], 'Many urgent dental visits are evaluation-and-stabilization visits first. The office should be able to explain whether they expect to diagnose, relieve pain, prescribe, or complete treatment the same day.', ['Ask what the visit is likely to accomplish', 'Ask whether x-rays or exam are included', 'Ask what follow-up may still be needed'], ['They imply everything is solved in one visit without context']),
      m('Emergency pricing and follow-up should be clear before you go', ['cost'], 'Urgent visits often separate the exam/triage cost from the treatment cost. Compare what the office says today’s fee includes and what might be additional.', ['Ask for the visit fee and likely add-ons', 'Ask what happens if treatment must continue later', 'Ask whether prescriptions or aftercare are included'], ['No one can explain what you are paying for today']),
      m('Use urgent care reviews for communication and follow-through, not only speed', ['reviews'], 'In urgent care, reliability matters as much as warmth. Look for whether patients mention clear instructions, symptom relief, and realistic follow-up.', ['Look for reviews about clarity and follow-through', 'Ask who to call if symptoms worsen after the visit', 'Ask whether the office handles rechecks'], ['Reviews repeatedly mention confusion or no follow-up'])
    ]
  ),
  '/dentistry/specialists/': makeConfig(
    'Quick answer',
    'Dental specialists are the right choice when the problem, procedure, or age group clearly falls outside routine general dentistry. The decision usually comes down to whether the office can explain why a specialist is or is not necessary.',
    'How to decide between a general dentist and a specialist',
    'Use this page to compare provider type, referral logic, and what kind of expertise actually matters for your problem.',
    ['Ask whether your issue belongs with a general dentist or a specialist', 'Ask what the specialist adds to the treatment plan', 'Ask whether records or imaging need to be transferred', 'Ask how follow-up works after specialist care', 'Do not let “we can handle it here” replace a clear explanation'],
    'What usually drives a specialist referral',
    ['Procedure complexity changes who should lead care.', 'Age, sedation needs, and anatomy can all matter.', 'A good office should explain the referral logic clearly.'],
    [
      m('Know the difference between general dental care and specialty care', ['specialists','endodontic','implant','orthodontic','pediatric'], 'The first question is what kind of provider is best suited for the issue. A clear answer should sound clinical and practical, not territorial.', ['Ask why a specialist is or is not recommended', 'Ask whether the case needs advanced equipment or training', 'Ask whether the general dentist will stay involved afterward'], ['They refuse to explain why specialist care may matter']),
      m('Compare referrals based on expertise, not convenience', ['compare'], 'A referral is useful when it improves the fit between the problem and the provider. Convenience matters, but it should not replace expertise when the treatment is more complex.', ['Ask how often the referred specialist handles your issue', 'Ask what changes if you stay in-house', 'Ask whether a second opinion would be reasonable'], ['You are steered only by office convenience or speed']),
      m('Pricing, records, and follow-up should still be clear', ['cost','records','follow-up'], 'Specialty care can add steps, records, and costs. Clarify how images, treatment notes, and follow-up are handled so the referral does not create confusion.', ['Ask who sends records and when', 'Ask who explains pricing and insurance', 'Ask who handles aftercare questions'], ['No one owns the handoff between offices'])
    ]
  ),
  '/trt/best-top-near-me/': makeConfig(
    'Quick answer',
    'People usually choose a TRT clinic by comparing prescriber oversight, baseline labs, follow-up cadence, dosing philosophy, and total monthly cost. The right clinic should feel medically structured, not like a fast subscription funnel.',
    'How to choose a TRT clinic safely',
    'Use the checklist first, then compare 2–3 clinics on monitoring, pricing, and who is actually making treatment decisions.',
    ['Confirm who prescribes and reviews your labs', 'Ask what baseline and follow-up labs are required', 'Ask how dose changes and side effects are handled', 'Ask what the monthly cost includes', 'Walk away from clinics that promise speed without medical detail'],
    'What usually separates a good clinic from a weak one',
    ['Monitoring and follow-up matter more than branding.', 'Pricing only makes sense once the treatment model is clear.', 'Fast-start promises are usually weaker than good clinical process.'],
    [
      m('Start with prescriber oversight and clinic type', ['evaluate a trt clinic','choose the right clinician','men’s health clinic','endocrinologist','primary care doctor','compare clinics'], 'The first comparison is who is responsible for treatment decisions. Good clinics can explain prescriber involvement, what kind of clinician you will work with, and how decisions are reviewed over time.', ['Ask who reviews labs and prescriptions', 'Ask whether care is physician-led, NP-led, or shared', 'Ask whether the provider explains why their model fits your needs'], ['No clear answer about who is responsible for medical decisions']),
      m('Baseline labs and monitoring should be explicit before you pay', ['labs','without labs','monitoring'], 'A trustworthy TRT clinic can tell you what baseline labs are required, when follow-up labs happen, and what would change the plan. Monitoring is not an optional detail.', ['Ask which baseline labs are standard', 'Ask when follow-up labs are repeated', 'Ask what happens if symptoms and labs do not match'], ['They offer TRT without baseline labs', 'They cannot explain follow-up cadence']),
      m('Use pricing questions to compare the full treatment model', ['pricing','coverage','cost'], 'The monthly number is only useful if you know what it includes: consults, labs, medication, supplies, follow-up visits, and refill support. Cheap plans become expensive when monitoring or meds are carved out.', ['Ask what the monthly fee includes', 'Ask which labs and medications are extra', 'Ask how refill or follow-up delays are handled'], ['The price sounds good but no one can explain inclusions']),
      m('Fast-start promises, high-dose culture, and telehealth shortcuts are real red flags', ['fast trt start','very high doses','telehealth'], 'Speed and convenience can be fine, but they should not replace medical judgment. Be especially cautious of clinics that minimize labs, overpromise symptom results, or normalize aggressive dosing without explanation.', ['Ask how they decide whether someone is a good candidate', 'Ask how they handle side effects or fertility concerns', 'Ask what would make them slow down or change the plan'], ['They frame caution as unnecessary', 'They market high doses or instant starts as a badge of honor']),
      m('Hair-loss treatment deserves a separate comparison path', ['hair-loss','hair transplant','prp hair'], 'Hair-loss clinics should be compared on a different set of questions than TRT. If the clinic offers both, ask where the treatment logic overlaps and where it does not.', ['Ask whether the same clinician handles hair-loss and TRT decisions', 'Ask how they separate cosmetic promises from medical planning', 'Ask what outcomes they can and cannot responsibly claim'], ['They blur cosmetic marketing into every part of the treatment conversation'])
    ]
  ),
  '/trt/cost-insurance/': makeConfig(
    'Quick answer',
    'TRT cost is usually a bundle question, not a single-price question. Compare consults, labs, medication, supplies, follow-up, and refill support before deciding whether a plan is really affordable.',
    'How to compare TRT cost before enrolling',
    'Use this page to compare what is included, what is recurring, and what can change the price after you start.',
    ['Ask for the full monthly and startup cost', 'Ask which labs, meds, and supplies are extra', 'Ask what insurance may or may not cover', 'Ask whether follow-up visits are included', 'Compare prices only after you compare monitoring quality'],
    'What usually drives TRT cost',
    ['Recurring support matters more than the headline number.', 'Coverage questions are specific to meds, labs, and provider model.', 'Low prices become expensive when monitoring is weak or carved out.'],
    [
      m('Know the startup cost versus the recurring monthly cost', ['cost','pricing'], 'TRT cost usually has at least two layers: getting started and staying on treatment. Compare both before you decide whether the program is actually sustainable.', ['Ask about consultation, onboarding, and baseline lab cost', 'Ask about the true monthly recurring total', 'Ask whether dose changes change the cost'], ['Only one number is quoted with no breakdown']),
      m('Labs, medication, and supplies may or may not be included', ['labs','medication','supply'], 'A plan that excludes labs, medications, or supplies can look cheap while costing more over time. Make the clinic explain what the quoted number really covers.', ['Ask which labs are included', 'Ask whether medication and syringes are included', 'Ask whether repeat labs cost extra'], ['No one can explain included vs extra items']),
      m('Insurance questions deserve plain-English answers', ['insurance','coverage'], 'Insurance coverage for TRT varies by the provider model, lab billing, and medication path. Ask specifically what they expect insurance to cover and what they do not.', ['Ask whether the clinic bills insurance directly', 'Ask whether meds are cash-pay only', 'Ask whether outside labs or pharmacies are allowed'], ['They say “insurance may help” with no specifics']),
      m('Use total cost to compare clinic quality, not just affordability', ['compare'], 'Price alone does not tell you whether a clinic is safe or useful. A higher fee may be reasonable if monitoring and follow-up are materially better; a lower fee is not a win if the process is sloppy.', ['Compare monitoring with the price', 'Compare access to the prescriber', 'Compare refill and follow-up reliability'], ['The clinic sells only on price and speed'])
    ]
  ),
  '/trt/safety-red-flags/': makeConfig(
    'Quick answer',
    'TRT safety red flags usually show up as weak screening, weak monitoring, weak side-effect planning, or high-pressure sales. If the clinic acts like caution is optional, treat that as the problem.',
    'How to spot TRT red flags before starting',
    'Use this page to compare whether the clinic acts like a medical program or a sales funnel.',
    ['Ask what makes someone a poor candidate', 'Ask how side effects are monitored', 'Ask how fertility concerns are handled', 'Ask how often the treatment plan is reviewed', 'Avoid clinics that normalize shortcuts'],
    'What safety usually requires',
    ['Screening matters before treatment starts.', 'Monitoring matters after the first prescription.', 'A good clinic can explain why not everyone should start immediately.'],
    [
      m('No-screening or low-screening intake is a major problem', ['without labs','safety'], 'A clinic should be able to explain who is and is not a good candidate before treatment starts. Minimal screening is not a convenience feature.', ['Ask what disqualifies someone or triggers caution', 'Ask what baseline evaluation is required', 'Ask whether symptoms alone are enough to start'], ['They are willing to prescribe before meaningful review']),
      m('Monitoring and side-effect planning should be concrete', ['side effects','monitoring'], 'Safety depends on how the clinic tracks side effects, symptoms, and lab changes over time. This should sound like a protocol, not a promise to “check in later.”', ['Ask how side effects are reviewed', 'Ask what happens if labs look off', 'Ask how quickly you can get help if something feels wrong'], ['No clear monitoring process', 'No plan for side-effect follow-up']),
      m('Fertility and long-term tradeoffs should not be brushed aside', ['fertility','family planning'], 'If fertility or future family planning matters, that should be part of the initial decision conversation. A clinic that ignores it is telling you how it thinks about risk.', ['Ask how fertility concerns change the plan', 'Ask what alternatives or protections are discussed', 'Ask whether your goals were actually heard'], ['They dismiss fertility concerns as irrelevant']),
      m('High-dose culture and fast-start marketing should raise concern', ['high doses','fast'], 'A clinic that treats aggressive dosing or instant starts as proof of quality is usually selling urgency instead of medical judgment.', ['Ask how they decide on dosing', 'Ask what would make them start lower, monitor longer, or delay treatment', 'Ask how they explain tradeoffs to patients'], ['They frame caution as weakness or bureaucracy'])
    ]
  ),
  '/neuro/best-top-near-me/': makeConfig(
    'Quick answer',
    'People usually choose a neuropsych evaluator by comparing specialty fit, report quality, timeline, communication style, and whether the evaluation will actually be useful for the school, work, or therapy goal they have in mind.',
    'How to choose a neuropsych evaluator',
    'Use the first call to clarify evaluator type, report usefulness, timing, and what kind of handoff happens after testing.',
    ['Confirm adult vs child specialty fit', 'Ask what the report includes and who uses it', 'Ask how long scheduling and results usually take', 'Ask whether the evaluator handles your exact concern often', 'Ask what next-step support happens after results'],
    'What usually drives a strong evaluator fit',
    ['Specialty fit matters before convenience.', 'Report usefulness matters more than testing jargon.', 'The right evaluator should explain the process in plain English.'],
    [
      m('Start with evaluator type and concern-specific fit', ['best','selection','adhd','autism','adult','child'], 'The first comparison is whether the evaluator regularly handles your exact concern and age group. The wrong fit can still produce a report, but not necessarily one that helps with the next step.', ['Ask whether they regularly evaluate your concern', 'Ask whether they focus on adults, children, or both', 'Ask whether they refer anything out'], ['They speak in generic terms about every condition or age group']),
      m('The report should be useful, not just comprehensive', ['report','results','documentation','school'], 'A good report should match the purpose of the evaluation. Ask how results are explained, what the written report includes, and whether it is commonly used for school, work, or treatment planning.', ['Ask what the final report includes', 'Ask whether recommendations are practical and specific', 'Ask how results are reviewed with you'], ['They cannot describe the report in concrete terms']),
      m('Timeline and communication quality matter more than they seem', ['timeline','cost','questions'], 'Neuro evaluations often involve long wait times and delayed reports. Good communication around timing, records, and expectations is part of the fit decision.', ['Ask how long scheduling usually takes', 'Ask how long the report takes after testing', 'Ask how they handle questions between booking and results'], ['They are vague about timing or process']),
      m('Insurance, accommodations, and follow-up should be discussed early', ['insurance','school','docs','therapy'], 'If you need the evaluation for insurance, school supports, workplace accommodations, or therapy planning, bring that up on the first call. It changes whether the fit is good enough.', ['Ask whether they handle your documentation goal often', 'Ask whether they coordinate with therapy or referral next steps', 'Ask what limits they want you to understand now'], ['They say “the report should work for everything” without qualification']),
      m('Trust and red flags usually show up in how questions are handled', ['trust','red flags'], 'A strong evaluator should be able to answer basic fit questions without acting like you are challenging them. Dismissiveness and vagueness are useful red flags.', ['Notice whether your questions improve clarity', 'Ask what would make them a poor fit for your case', 'Compare more than one option if the first call feels off'], ['They act irritated by basic process questions'])
    ]
  ),
  '/neuro/cost-timeline/': makeConfig(
    'Quick answer',
    'Neuro evaluation cost and timeline depend on the scope of testing, the kind of report you need, scheduling demand, and whether insurance plays any role. The useful comparison is what you get, when you get it, and whether it serves the decision you actually need to make.',
    'How to compare neuro evaluation cost and timing',
    'Use this page to compare testing scope, scheduling expectations, report timing, and what can create delays or extra cost.',
    ['Ask what the quoted price includes', 'Ask whether report writing and feedback are included', 'Ask how long scheduling and final results usually take', 'Ask what insurance may or may not cover', 'Ask what can create delays or extra appointments'],
    'What usually changes cost and timing',
    ['Testing scope drives the price.', 'Report depth and documentation goals drive the timeline.', 'Insurance does not remove the need for a clear process explanation.'],
    [
      m('Start with what the evaluation includes', ['cost','what is included'], 'The right question is not just “how much?” but “what is included?” Testing, scoring, report writing, and results review may or may not all be part of the quoted total.', ['Ask whether feedback and report writing are included', 'Ask whether additional appointments are separate', 'Ask whether records review is included'], ['Only a flat number with no scope explanation']),
      m('Scheduling and report timing deserve exact questions', ['timeline','how long'], 'Wait times and report timing vary a lot. A good practice can tell you the typical time to first appointment and the typical time from testing to final report.', ['Ask for the normal scheduling range', 'Ask how long reports usually take', 'Ask whether urgent documentation needs can be discussed'], ['They are vague about every timeline question']),
      m('Insurance and documentation needs can change the path', ['insurance','school','docs'], 'Insurance can affect the route into care, but it does not tell you whether the final evaluation product is right for your goal. Documentation needs should be discussed early.', ['Ask what insurance covers, if anything', 'Ask whether the evaluation supports school/work documentation needs', 'Ask whether reimbursement paperwork is provided'], ['They imply insurance automatically solves fit or documentation issues']),
      m('Delays usually come from records, scope changes, or handoff issues', ['delay'], 'Many delays happen because records are missing, the scope changes mid-process, or the report/recommendation handoff is not planned clearly.', ['Ask what documents or records help now', 'Ask what could slow the process down', 'Ask what happens if the concern changes during testing'], ['No one can explain common delay points'])
    ]
  ),
  '/neuro/trust-questions/': makeConfig(
    'Quick answer',
    'Trust in neuro evaluation usually comes from specialty fit, clear process explanations, realistic timelines, and whether the evaluator can explain what the report will and will not do. Good fit should sound calm, specific, and practical.',
    'What to ask before booking a neuro evaluation',
    'Use this page to compare how evaluators explain fit, process, report usefulness, and next steps before you commit.',
    ['Ask what concerns they handle most often', 'Ask what the report is meant to help with', 'Ask how results are reviewed and explained', 'Ask what a poor fit would look like', 'Ask how follow-up or referral next steps work'],
    'What trust usually sounds like here',
    ['A good evaluator explains limits clearly.', 'Process clarity matters as much as credentials.', 'You should understand what happens before, during, and after testing.'],
    [
      m('Use the first call to test specialty fit and scope clarity', ['trust','legit','questions'], 'A strong evaluator should be able to tell you whether your concern and age group fit their practice and whether another type of provider might make more sense.', ['Ask what concerns they see most often', 'Ask whether they think your concern fits their evaluation model', 'Ask what they would refer out'], ['They treat every concern as the same']),
      m('Ask what the report will actually help you do', ['report','school','work','therapy'], 'The report is only valuable if it helps with the decision you care about. Ask how the report is used and what kinds of recommendations are typical.', ['Ask whether the report supports your goal', 'Ask how recommendations are framed', 'Ask whether they review results with you in plain language'], ['They cannot explain what the report is good for']),
      m('Timeline, communication, and records handling are trust signals', ['timeline','updates','records'], 'How a practice handles booking, records, scheduling, and follow-up tells you a lot about what the full process will feel like.', ['Ask what they need before booking', 'Ask how scheduling updates are handled', 'Ask how questions are answered between appointments'], ['The process already feels vague or disorganized']),
      m('A good evaluator should be able to describe poor fit and limitations', ['red flags','poor fit'], 'Trust improves when the evaluator can explain what they may not be the best fit for. Limit-setting is usually a positive sign in this context.', ['Ask what kinds of cases are not ideal for them', 'Ask what they would want you to know before booking', 'Ask whether another path could make more sense'], ['They act like there are no fit limitations at all'])
    ]
  ),
  '/neuro/situations/': makeConfig(
    'Quick answer',
    'Situation-specific neuro questions are usually about what changed, what decision you need to make, and what kind of evaluation or therapy support would actually move things forward. The page works best as a triage tool for complex scenarios.',
    'How to use neuro situation questions',
    'Use this page to identify whether you need evaluation, therapy fit, documentation help, or a different next step entirely.',
    ['Clarify what changed and what decision is stuck', 'Identify whether the issue is evaluation, therapy, documentation, or all three', 'Write down who needs the result or recommendation', 'Ask what part of the process is actually missing', 'Use the local guide once the situation stops being generic'],
    'What usually changes by situation',
    ['The decision goal matters as much as the symptom description.', 'Different situations need different provider types.', 'Documentation and handoff needs often drive the next step.'],
    [
      m('Start by defining the decision or blockage clearly', ['situation','what if','common situations'], 'Many situation pages are really decision pages in disguise. Define what is stuck: diagnosis, school support, therapy fit, work documentation, or something else.', ['Write the practical goal in one sentence', 'Identify who needs the result', 'Identify what information is missing'], ['The goal is still too vague to compare options']),
      m('Use provider type, documentation needs, and next-step support to narrow the path', ['school','work','college','report','therapy','evaluation','testing','diagnosis','support'], 'Some situations need a full evaluation, some need therapy matching, and some need documentation support. The right next step depends on what outcome you actually need from the process.', ['Ask whether evaluation or therapy is the real need', 'Ask whether documentation is part of the goal', 'Ask what the shortest useful next step is'], ['You are steered into a full workup without a clear reason']),
      m('Urgency, deadlines, and after-results decisions change what to do next', ['deadline','quickly','prepare','bring','after results','updated later','re-testing','medication','now what','comes next'], 'When the issue involves a deadline, post-results next step, or follow-up decision, compare what help is time-sensitive and what can wait. This keeps the process practical instead of overwhelming.', ['Ask what must happen first', 'Ask what can wait until after results', 'Ask who should receive or act on the report next'], ['No one can explain the next decision after testing']),
      m('Move to the local guide when the situation becomes practical', ['local'], 'Once the question becomes local, time-sensitive, or provider-specific, move to the official local guide. Situation pages should orient you before the local choice, not replace it.', ['Use this page to frame the issue', 'Move to local routing for the action step', 'Keep the question list with you when you compare providers'], ['You stay in summary mode when you really need local next steps'])
    ]
  ),
  '/uscis-medical/civil-surgeon-near-me/': makeConfig(
    'Quick answer',
    'People usually choose a civil surgeon by verifying USCIS authorization, asking exactly what is included, confirming vaccine and records handling, and making sure the clinic can move the paperwork correctly and on time.',
    'How to choose a civil surgeon without causing delays',
    'Use the first call to verify authorization, document handling, timing, and what could force you to redo part of the process.',
    ['Verify the doctor is an authorized civil surgeon', 'Ask what documents and vaccine records to bring', 'Ask exactly what the quoted fee includes', 'Ask how the sealed I-693 is handled and when it is ready', 'Ask what issues commonly create delays or repeat visits'],
    'What usually matters most here',
    ['Authorization and paperwork handling come first.', 'Cheap pricing is risky if records and timing are unclear.', 'The best clinic should make the process easier to predict, not more confusing.'],
    [
      m('Start with USCIS authorization and clinic legitimacy', ['authorized','verify','compare civil surgeons','top rated','legit'], 'Before anything else, confirm the physician is an authorized civil surgeon and that the clinic can explain the USCIS medical process clearly. The first call should sound procedural, not improvisational.', ['Ask for the physician name and authorization confirmation', 'Ask how often they handle I-693 exams', 'Ask what part of the process happens at the clinic vs elsewhere'], ['They cannot clearly confirm civil-surgeon status', 'They sound uncertain about the USCIS process']),
      m('Ask what documents, vaccines, and records are needed', ['documents','vaccines','old vaccine records','no records','translator','pregnant','tb history'], 'Many avoidable problems come from missing records, vaccine confusion, or not knowing what special circumstances change the visit. Ask these questions before you book.', ['Ask exactly what ID and records to bring', 'Ask how missing vaccine records are handled', 'Ask whether special situations change the process'], ['They say “just come in” without document guidance']),
      m('Use pricing questions to compare what the clinic actually includes', ['pricing','same-day','walk-in','urgent availability'], 'Price is only useful if you know what it covers. Ask whether labs, vaccines, extra visits, translations, or follow-up handling are included or separate.', ['Ask whether labs or vaccines cost extra', 'Ask whether same-day or walk-in care changes the price', 'Ask what happens if additional testing is required'], ['A low quote is given with no explanation of what is excluded']),
      m('Sealed packet handling and timing should be crystal clear', ['sealed envelope','mail results','how long','avoid delays','redoing the exam'], 'The clinic should be able to explain when the I-693 will be ready, how the sealed packet is handled, and what can force a repeat visit or correction.', ['Ask when the sealed packet is ready', 'Ask whether anything can delay release', 'Ask how corrections are handled if needed'], ['They are vague about packet timing or corrections']),
      m('Use the consultation to compare 2–3 clinics quickly', ['compare 2–3','how to compare'], 'A useful comparison looks simple: authorization, included services, document clarity, packet timing, and how confidently the clinic explains the process.', ['Use the same questions with every clinic', 'Write down timing and included-cost answers', 'Choose the clinic that makes the process easiest to predict'], ['You choose only on distance or the lowest starting price'])
    ]
  ),
  '/uscis-medical/cost/': makeConfig(
    'Quick answer',
    'USCIS medical cost varies because some clinics bundle the exam, paperwork, vaccines, and labs differently. The safest comparison is total expected cost plus a clear explanation of what could trigger extra charges or a repeat visit.',
    'How to compare USCIS exam cost',
    'Use this page to compare the exam fee, common add-ons, and what a low quote may be leaving out.',
    ['Ask whether the quoted price includes form handling', 'Ask whether vaccines or labs are extra', 'Ask whether repeat visits or corrections cost more', 'Ask when payment is due and what is refundable', 'Compare total expected cost, not just the entry price'],
    'What usually changes the USCIS medical price',
    ['Bundling differences matter.', 'Vaccines, labs, and repeat handling can add cost.', 'A cheap quote is risky if timing or paperwork handling is weak.'],
    [
      m('Start with what the clinic says the quote includes', ['cost','price'], 'The quoted number may include only the visit, or it may include paperwork handling, some labs, and parts of the vaccine review. Ask exactly what is included before you compare clinics.', ['Ask whether the quote includes I-693 handling', 'Ask whether the quote includes any labs or vaccines', 'Ask whether a review of existing records is included'], ['No one can explain the quote clearly']),
      m('Vaccines, labs, and extra visits are the usual add-ons', ['vaccines','labs'], 'Extra cost often comes from missing vaccines, required labs, or the need to return. Those add-ons should not be treated like surprises.', ['Ask which labs are commonly extra', 'Ask what happens if vaccines are missing', 'Ask whether follow-up visits cost more'], ['The clinic downplays common add-ons']),
      m('Use low-price offers carefully', ['cheap','low'], 'A low entry price can still be reasonable, but only if the clinic is clear about what the number does and does not cover. Compare transparency, not just the quote.', ['Ask what could raise the total', 'Ask whether corrections or reprints cost more', 'Ask whether the clinic expects another visit'], ['The quote sounds unusually low and no one explains why']),
      m('Timing and correction handling can make a “cheap” exam expensive', ['delay','correction'], 'If paperwork handling is sloppy, the cheapest clinic can become the most expensive through delays and repeat visits. Cost comparison should include process reliability.', ['Ask how corrections are handled', 'Ask what happens if something is missing', 'Ask whether the clinic has a standard process for rework'], ['No correction or rework process is explained'])
    ]
  ),
  '/uscis-medical/delays-rfe/': makeConfig(
    'Quick answer',
    'USCIS medical delays usually happen because records are incomplete, vaccine or lab steps are unclear, the sealed packet is mishandled, or the clinic fails to explain what is still missing. Most delays are process failures, not mysterious immigration problems.',
    'How to avoid delays and RFEs',
    'Use this page to identify what commonly goes wrong and what to verify before and after the exam.',
    ['Ask what documents or records are still missing', 'Ask when the sealed packet will be ready', 'Ask what situations commonly cause rework', 'Ask what to do if something changes after the exam', 'Do not leave the clinic unclear about the next step'],
    'What usually creates avoidable delay',
    ['Incomplete records create confusion fast.', 'Packet handling mistakes are expensive.', 'The clinic should be able to explain the process in a predictable sequence.'],
    [
      m('Missing or unclear records are a common source of delay', ['delay','rfe','missing','records'], 'Many delays start because records, vaccine proof, or special circumstances were not clarified early. The clinic should be able to tell you what is still missing before the visit ends.', ['Ask what records are still needed', 'Ask whether old records are acceptable', 'Ask whether missing items can be handled after the visit'], ['The clinic cannot tell you what is missing']),
      m('Packet timing and sealed-form handling need exact answers', ['sealed','packet','mail','ready'], 'The I-693 process depends on correct sealed-form handling. Ask when it is ready, who gives it to you, and what to do if timing changes.', ['Ask when the packet is ready', 'Ask whether the packet can be mailed and how', 'Ask what to do if you cannot pick it up immediately'], ['The clinic is casual about sealed-form handling']),
      m('Labs, vaccines, and special circumstances can create extra steps', ['labs','vaccines','pregnant','tb','translator'], 'Extra steps are not automatically a problem if the clinic explains them early. They become a problem when they appear late and without a clear process.', ['Ask what special circumstances change the timeline', 'Ask what follow-up is required if labs or vaccines are pending', 'Ask what the clinic will tell you after results return'], ['No one can explain the follow-up path for exceptions']),
      m('Good clinics make the next step unambiguous', ['avoid'], 'At the end of the visit you should know what has been completed, what remains open, and what happens next. If that sequence is muddy, delay risk goes up fast.', ['Ask what is complete today', 'Ask what remains open', 'Ask when you should follow up if you do not hear back'], ['You leave without a clear next-step sequence'])
    ]
  ),
  '/uscis-medical/process-documents/': makeConfig(
    'Quick answer',
    'The USCIS medical exam is mostly a document and process workflow: choose an authorized civil surgeon, bring the right records, complete the visit and any required labs or vaccines, and receive the correctly handled I-693 packet on the right timeline.',
    'How the USCIS medical process works',
    'Use this page as the step-by-step process guide for what to bring, what happens during the visit, and how the paperwork moves afterward.',
    ['Verify the doctor is an authorized civil surgeon', 'Bring ID, immigration paperwork, and vaccine records', 'Ask what the clinic still needs before you leave', 'Ask how labs, vaccines, and follow-up are handled', 'Confirm when and how the sealed I-693 will be ready'],
    'What the process usually depends on',
    ['Authorization comes first.', 'Records and vaccines affect the visit flow.', 'Packet handling and timing affect the final next step.'],
    [
      m('Start with the authorized civil surgeon and booking step', ['process','start','civil surgeon'], 'The process begins with booking an authorized civil surgeon who can explain what documents, records, and payment details matter before the exam day.', ['Ask whether the doctor is a current civil surgeon', 'Ask what to bring before you arrive', 'Ask whether any records should be sent in advance'], ['The office cannot clearly explain the pre-visit process']),
      m('Bring the right documents and vaccine records', ['bring','documents','records','translator'], 'Bring identification, immigration-related paperwork if requested, and any vaccine or medical records you have. Missing documents do not always end the process, but they can change the visit.', ['Ask which documents are essential', 'Ask how to handle incomplete vaccine history', 'Ask whether a translator or support person changes anything'], ['The office treats records as an afterthought']),
      m('Know what happens during the visit and any added testing', ['exam works','lab','tb','pregnant'], 'The exam may include record review, physical evaluation, vaccine review, and labs if needed. A good clinic can tell you the sequence in plain English.', ['Ask what happens first, second, and third', 'Ask whether labs are done on site or elsewhere', 'Ask what happens if special circumstances apply'], ['The clinic cannot explain the visit sequence']),
      m('Use packet timing and follow-up handling as a final check', ['sealed','mail','avoid delays','redoing'], 'The last process question is what happens to the completed I-693: when it is ready, how it is handled, and what could require follow-up or correction.', ['Ask when the packet is ready', 'Ask whether corrections are possible if needed', 'Ask what to do if you do not hear back'], ['The office is vague about the packet and follow-up'])
    ]
  ),

  '/personal-injury/best-top-near-me/': makeConfig(
    'Quick answer',
    'If you are trying to find the best personal injury lawyer near you, focus on five things first: where the lawyer shows up, what past clients say, whether the lawyer handles your kind of case, how the consultation feels, and how the contingency fee is explained. The goal is not to find the loudest advertiser. The goal is to find a lawyer with relevant experience, clear communication, and a fee structure you understand before you sign anything.',
    'How to Find the Best Personal Injury Lawyer Near You',
    'Use this checklist above the fold before you let “best” or “top rated” language drive the decision.',
    ['Start with real legal directories and the lawyer\'s own site', 'Read reviews for patterns, not one-off praise', 'Verify experience with your kind of case', 'Compare more than one consultation', 'Confirm the contingency fee and case costs in writing', 'Ask who will actually handle the case day to day'],
    'What usually separates a strong PI firm from a weak one',
    ['Relevant case experience matters more than hype.', 'Fee math matters because it changes your net recovery.', 'Clear communication and trial readiness matter more than directory swagger.', 'A calm, specific consultation is usually a better signal than a flashy intake script.'],
    [
      m('How to Find the Best Personal Injury Lawyer Near You', ['best personal injury lawyer near me','top accident attorney near me','#1 car accident lawyer','highest rated injury lawyer','most experienced accident lawyer'], 'Start with where the lawyer shows up, what real clients say, whether the lawyer handles your kind of case, how the consultation feels, and how the contingency fee is explained. “Best” is not a trophy question. It is a filtering question.', ['Start with real legal directories and the lawyer\'s own site', 'Read reviews for patterns, not one-off praise', 'Verify experience with your exact case type', 'Compare more than one consultation', 'Confirm the contingency fee and case costs in writing'], ['Pressure to sign on the first call', 'No clear explanation of who will handle the case', 'Vague answers about fees or litigation experience']),
      m('What to Compare During a Personal Injury Consultation', ['consultation','who handles','free consultation','day-to-day contact'], 'Use the consultation to compare who will actually manage the case, how updates will work, whether the firm can explain your next steps in plain English, and whether the fee agreement is specific about percentages, expenses, and what changes if the case moves into litigation.', ['Ask who your day-to-day contact will be', 'Ask how often updates happen', 'Ask whether the lead lawyer stays involved after intake', 'Ask what changes if the case must be filed', 'Ask for the fee agreement before signing'], ['The signer disappears after intake', 'Communication expectations stay vague']),
      m('How to Read Reviews and Results Without Getting Fooled', ['reviews','results','millions recovered'], 'Reviews and result pages can help, but only when you read them as evidence instead of advertising. Look for detail, consistency, and whether the firm can explain the kinds of cases behind any large numbers it advertises.', ['Look for specific review detail, not only volume', 'Ask what kinds of cases produced the quoted results', 'Compare whether the firm explains both settlements and litigation'], ['Only vague “millions recovered” claims', 'Reviews feel generic or heavily scripted']),
      m('Why Trial Readiness and Local Fit Matter', ['trial','county','venue','local fit'], 'When liability, damages, or negotiation become contested, local practice patterns and trial readiness can matter more than ad visibility. A strong firm should be able to explain what changes if the case has to be filed.', ['Ask how local judges or insurers affect strategy', 'Ask what happens if the case must be filed', 'Ask whether they regularly work in your county or venue'], ['They say local rules never matter', 'They cannot explain what changes if negotiation fails'])
    ]
  ),
  '/personal-injury/trust-red-flags/': makeConfig(
    'Quick answer',
    'If you are wondering about red flags when hiring a personal injury lawyer, the safest place to start is with behavior you can spot early: pressure to sign fast, vague answers about fees, weak communication, and no clear explanation of who will actually handle your case. A good lawyer should make the process easier to understand, not harder.',
    'Red Flags to Watch Out for When Hiring a Personal Injury Lawyer',
    'Use this checklist before you sign with anyone who sounds polished but leaves you confused.',
    ['Pressure to sign immediately', 'No clear fee explanation in writing', 'Vague answers about who handles the case', 'Promises of a guaranteed result', 'Poor communication during intake', 'Little discussion of case weaknesses', 'Dismissive answers to basic questions'],
    'What trust usually means here',
    ['Trust usually shows up in specifics, not branding.', 'Pressure, promises, and silence are stronger signals than marketing.', 'A good consultation should leave you clearer than you were before it started.'],
    [
      m('Red Flags to Watch Out for When Hiring a Personal Injury Lawyer', ['red flags','scam','pressure'], 'The easiest red flags to spot early are pressure to sign fast, vague answers about fees, weak communication, and no clear explanation of who will actually handle your case. A good lawyer should make the process easier to understand, not harder.', ['Pressure to sign immediately', 'No clear fee explanation in writing', 'Vague answers about who handles the case', 'Promises of a guaranteed result', 'Poor communication during intake', 'Little discussion of case weaknesses'], ['Guaranteed payout language', 'Artificial urgency', 'No written fee breakdown']),
      m('How to Tell Whether an Injury Lawyer Is Legit', ['legit','license','discipline','bar'], 'Start with bar status, fee clarity, communication, and whether the lawyer can explain realistic risk without sales pressure. Trust usually shows up in specifics: who will represent you, how settlement authority works, and how often you should expect updates.', ['Check the state bar listing', 'Ask for the full attorney name before signing', 'Ask who controls settlement decisions', 'Ask how often updates happen', 'Compare more than one firm if anything feels off'], ['They resist giving the attorney name', 'They act like comparison shopping is a problem']),
      m('Why Communication Problems Usually Get Worse', ['won’t call me back','updates','call me back','communication','reviews','compare'], 'If communication already feels sloppy during intake, assume it will feel worse once the file is signed. Clear update expectations are part of basic trust.', ['Ask how often you should expect updates', 'Ask who answers urgent questions', 'Ask how to reach the person actually running the file'], ['Slow or evasive intake responses', 'No clear contact person']),
      m('What to Protect While You Are Still Deciding', ['recorded statement','post about my accident','sharing details','social media','verify before signing','fees','signing'], 'Before you choose counsel, avoid careless disclosures that can complicate the claim. Intake convenience should not push you into sharing more than necessary or posting about the incident publicly.', ['Be careful with recorded statements', 'Avoid posting claim details online', 'Ask before sharing sensitive documents broadly'], ['They encourage risky public or insurer disclosures', 'They do not explain basic claim-protection habits'])
    ]
  ),
  '/personal-injury/cost-fees/': makeConfig(
    'Quick answer',
    'Most personal injury lawyers work on a contingency fee, which means the lawyer is paid from the recovery instead of through hourly billing up front. The two biggest things to understand are the percentage fee and the separate case expenses. You should also ask what you owe if the case does not recover money.',
    'How Much Does a Personal Injury Lawyer Cost?',
    'Read this cost checklist first so “no fee unless you win” does not hide the real math.',
    ['Ask for the contingency percentage in writing', 'Ask whether the percentage changes if the case is filed or tried', 'Ask how case expenses are tracked', 'Ask whether expenses are deducted before or after the fee', 'Ask what you owe if the case loses', 'Ask for a worked dollar example'],
    'What usually changes your net recovery',
    ['The fee percentage is only one line item.', 'Case expenses are separate from the attorney fee.', 'Liens and deductions affect what you actually keep.', 'A vague contract can cost more than a slightly higher but clearer percentage.'],
    [
      m('How Much Does a Personal Injury Lawyer Cost?', ['how much','cost','percentage','up front'], 'Many personal injury lawyers charge a contingency fee of around one-third before suit and more if the case moves deeper into litigation. The real question is not just the percentage. It is also how expenses are handled and what happens if the case does not recover money.', ['Ask for the contingency percentage in writing', 'Ask whether the percentage changes if the case is filed or tried', 'Ask how case expenses are tracked', 'Ask whether expenses are deducted before or after the fee', 'Ask what you owe if the case loses'], ['Only a flat percentage with no explanation of expenses', 'No written fee agreement']),
      m('How Do Contingency Fees Work?', ['contingency','free consultation','do i pay if we lose','plain english'], 'A contingency fee means the lawyer takes a percentage of the recovery if the case brings in money. Case expenses are separate from the attorney fee, so you should ask for the exact order of deductions and a worked example of what the net payout would look like.', ['Ask for a worked dollar example', 'Ask whether liens are estimated in the example', 'Ask what happens if the case switches firms', 'Ask whether costs stay your responsibility if there is no recovery'], ['They treat attorney fees and case costs like the same thing']),
      m('Attorney Fees vs. Case Expenses', ['hidden fees','case costs','costs handled','expenses'], 'Attorney fees are the lawyer’s percentage. Case expenses are the out-of-pocket costs of building and pursuing the claim. Those are not the same thing, and you should not let them get blurred together.', ['Ask whether filing fees, records, experts, and investigators are separate', 'Ask whether costs are advanced or billed as they occur'], ['They blur expenses into the fee explanation']),
      m('What You Pay If You Lose and What the Net Settlement May Look Like', ['lose','net settlement','lien','medical bills','payout'], 'Many contingency arrangements mean no attorney fee is owed if there is no recovery, but you still need to ask whether any case expenses remain your responsibility. Before signing, ask for sample math showing how the gross settlement turns into the net amount you receive.', ['Ask what happens to expenses if there is no recovery', 'Ask for sample math using a realistic settlement number', 'Ask how liens and medical reimbursements affect the net'], ['They will not show the payout math in writing'])
    ]
  ),
  '/personal-injury/settlement-offers/': makeConfig(
    'Quick answer',
    'A settlement offer is not fair just because it arrives quickly. The better question is whether the offer actually accounts for medical costs, lost wages, pain and suffering, future expenses, and the strength of liability. If those categories are still unclear, speed usually benefits the insurer more than you.',
    'Signs a Settlement Offer Is Fair',
    'Use this checklist before you let a fast insurer timeline become your valuation method.',
    ['Medical costs are actually covered', 'Lost wages are included', 'Pain and suffering is not treated like zero', 'Future expenses are considered', 'Liability strength is reflected', 'The math is explained clearly'],
    'What usually changes settlement fairness',
    ['Fast offers can be useful data without being fair offers.', 'Fairness depends on damage categories, not only one big number.', 'A release matters because it often closes the claim for good.'],
    [
      m('Signs a Settlement Offer Is Fair', ['how do i know if a personal injury settlement offer is fair','how do i know if an injury settlement offer is too low'], 'A settlement offer is not fair just because it arrives quickly. The better question is whether the offer actually accounts for medical costs, lost wages, pain and suffering, future expenses, and the strength of liability.', ['Medical costs are actually covered', 'Lost wages are included', 'Pain and suffering is not treated like zero', 'Future expenses are considered', 'Liability strength is reflected', 'The math is explained clearly'], ['The offer arrives before treatment is clearer', 'The insurer cannot explain the math']),
      m('Should You Accept the First Settlement Offer?', ['should i accept the first settlement offer'], 'Usually not until you understand what the offer includes, what is still missing, and whether treatment or damages are still developing. A first offer can be useful data, but it should not force a decision before the claim is mature enough to evaluate.', ['Ask what damage categories the offer includes', 'Ask what records or treatment are still missing', 'Ask what rights you give up when you sign a release'], ['Pressure to sign before the medical picture is stable']),
      m('When Negotiation Usually Starts and What Can Change It', ['negotiation usually start','demand','timing'], 'Real negotiation usually starts after enough medical and liability information exists to value the claim with some confidence. A rushed offer often tells you more about the insurer\'s timing than about the value of the case.', ['Ask what information the insurer is still waiting on', 'Ask whether the demand package is complete', 'Ask what changes if negotiation starts before treatment is clearer'], ['They act like negotiation timing has nothing to do with treatment or records']),
      m('What a Release Means Before You Sign It', ['release','reopen'], 'Usually, a signed release closes the claim. That is why fairness review matters before you sign anything that gives up future rights.', ['Read what claims the release covers', 'Confirm whether future treatment is still uncertain'], ['You are being pushed to sign a release before you understand the full damage picture'])
    ]
  ),
  '/personal-injury/insurance-fault/': makeConfig(
    'Quick answer',
    'After an accident, the safest recorded-statement answer depends on which insurer is asking and why. Your own insurer and the opposing insurer do not present the same level of risk. Your own policy may require cooperation, but the opposing insurer often wants a statement before you fully understand the claim.',
    'Should You Give a Recorded Statement?',
    'Use this decision split first: your own insurer is not the same as the opposing insurer.',
    ['Separate your own insurer from the opposing insurer', 'Stick to basic facts and do not guess', 'Do not minimize injuries or speculate about fault', 'Ask what your policy requires before agreeing to a recorded statement', 'Treat repeated adjuster calls like claim activity, not casual conversation'],
    'What usually matters most in insurer communication',
    ['Who is asking matters.', 'Facts are safer than guesses.', 'Early recorded statements can lock you into details before the claim is clear.', 'Fault and coverage questions often get worse when you speak loosely.'],
    [
      m('Should You Give a Recorded Statement?', ['recorded statement','insurance company after an accident','give a recorded statement'], 'The safest answer depends on which insurer is asking and why. Your own insurer and the opposing insurer do not present the same level of risk. Your own policy may require cooperation, but the opposing insurer often wants a recorded statement that locks you into details before you fully understand the claim.', ['Separate your own insurer from the opposing insurer', 'Stick to basic facts and do not guess', 'Do not minimize injuries or speculate about fault', 'Ask what your policy requires before agreeing to a recorded statement'], ['Treating every insurer call like a casual chat', 'Guessing about speed, fault, or medical prognosis']),
      m('What to Do When the Insurance Adjuster Keeps Calling', ['calls me every day','adjuster calls me every day','insurance adjuster calls me every day'], 'Repeated adjuster calls do not change the rule that you should stay factual, avoid speculation, and avoid letting the tone of the call make you forget that the claim is being evaluated. Pressure and friendliness can both be tactics for getting broad statements too early.', ['Keep answers short and factual', 'Do not fill silent gaps by guessing', 'Do not let repeated calls push you into a broad recorded interview'], ['You start answering new questions just to end the calls']),
      m('Can You Still Recover if You Were Partly at Fault?', ['partly at fault','comparative fault'], 'Maybe. Partial-fault rules depend on state law, but the practical issue is that your words to the insurer can make fault arguments better or worse before the evidence is fully developed.', ['Ask how comparative fault works in your state', 'Be careful about casual admissions on insurer calls'], ['You treat “partly my fault” like a simple yes-or-no issue without checking state rules']),
      m('What Happens if the Other Driver Has No Insurance?', ['no insurance','uninsured'], 'The next step depends on whether uninsured or underinsured coverage applies, what the injury picture looks like, and whether other recovery paths exist. Do not make loose statements just because the coverage question feels urgent.', ['Check whether UM or UIM coverage may apply', 'Keep insurer communications factual while coverage is sorted out'], ['You assume no insurance means no claim without checking your own coverage'])
    ]
  ),
  '/personal-injury/process-timeline/': makeConfig(
    'Quick answer',
    'A personal injury case is easier to understand as phases instead of one single number. Intake and investigation may take days to a few weeks, treatment and case development can take weeks or months, pre-suit negotiation can take weeks to months, and litigation can add many more months if the case does not settle early.',
    'How Long Does a Personal Injury Lawsuit Take From Start to Finish?',
    'Use the phase-by-phase timeline first so “how long will this take?” turns into a real checklist instead of one vague estimate.',
    ['Initial investigation and intake', 'Medical treatment and case development', 'Demand and pre-suit negotiation', 'Lawsuit filing and discovery', 'Mediation or renewed settlement talks', 'Trial preparation and trial'],
    'What usually drives the timeline',
    ['Treatment pace changes valuation timing.', 'Liability disputes slow everything down.', 'Pre-suit and post-filing negotiation are different stages.', 'The same case can move quickly in one phase and stall in another.'],
    [
      m('How Long Does a Personal Injury Lawsuit Take From Start to Finish?', ['start to finish','usually take','timeline'], 'The easiest way to understand timing is to break the case into phases instead of asking for one single number. Intake and investigation may take days to a few weeks, treatment and case development can take weeks or months, pre-suit negotiation can take weeks to months, and litigation can add many more months if the case does not settle early.', ['Initial investigation and intake', 'Medical treatment and case development', 'Demand and pre-suit negotiation', 'Lawsuit filing and discovery', 'Mediation or renewed settlement talks', 'Trial preparation and trial'], ['Anyone gives you one exact number without explaining the phase that is still unknown']),
      m('What Happens During Each Phase of a Personal Injury Case', ['what happens after i sign','what happens'], 'After you sign, the usual next steps are investigation, records collection, insurance notice, treatment tracking, and claim-building. If the case does not settle pre-suit, the timeline shifts into filing, discovery, motions, negotiation, and possibly trial preparation.', ['Confirm what records or documents they need first', 'Ask what can delay the timeline', 'Ask when a demand usually goes out', 'Ask what changes if the case must be filed'], ['No one can explain the next stage after intake']),
      m('When Should You Talk to a Lawyer After an Accident?', ['when should i talk'], 'It usually helps to talk to a lawyer before recorded statements, early settlement pressure, or deadline confusion turn a simple claim into a mess. Early contact matters most when fault is disputed, injuries are getting clearer over time, or the insurer is already pushing for quick statements or releases.', ['Talk early if the insurer is asking for a recorded statement', 'Talk early if liability is disputed', 'Talk early if treatment is still unfolding'], ['You wait until after signing a release to ask bigger questions']),
      m('How Long Does Settlement Negotiation Usually Last?', ['settlement negotiation'], 'Settlement negotiation can be short or drawn out depending on treatment status, fault disputes, and whether the insurer believes the case may actually be filed. A negotiation timeline only makes sense when you know what stage the case is in and what information is still missing.', ['Ask whether the case is still missing treatment records', 'Ask what usually triggers a real insurer response', 'Ask what changes if pre-suit negotiation stalls'], ['They discuss negotiation timing without explaining treatment or evidence gaps'])
    ]
  ),
  '/personal-injury/medical-treatment/': makeConfig(
    'Quick answer',
    'Medical treatment questions after an accident usually come down to timing, follow-up, and documentation. The main issue is not just where you go first — it is whether the care path makes medical sense and creates a clean record of what happened and how symptoms developed.',
    'How to handle treatment decisions after an accident',
    'Use this page to decide what needs attention now, what can wait briefly, and how treatment timing affects both health and claim strength.',
    ['Get urgent symptoms checked immediately', 'If symptoms appear later, document when they started and get seen promptly', 'Follow through on recommended care when possible', 'Do not create unexplained treatment gaps if you can avoid them', 'Keep every discharge note, referral, and bill organized'],
    'What usually matters most in treatment decisions',
    ['The first visit should match the urgency of symptoms.', 'Delayed symptoms still count, but they should be documented clearly.', 'Treatment gaps create confusion unless they can be explained.', 'Medical records become part of the case timeline whether you like it or not.'],
    [
      m('Know when ER, urgent care, or a doctor visit makes sense', ['urgent care','er after a crash'], 'The first question is medical urgency. Severe symptoms, head injury concerns, breathing issues, or obvious emergency signs justify higher-level care immediately; less urgent symptoms may fit urgent care or a doctor visit faster and more efficiently.', ['Match the level of care to the severity of symptoms', 'Save discharge paperwork from the first visit', 'Ask what follow-up is recommended before you leave'], ['You ignore serious symptoms because the claim seems “not that bad”']),
      m('Delayed symptoms need a clean timeline, not panic', ['delaying treatment'], 'Delayed pain or stiffness is common after crashes and falls, but once symptoms appear you want a clean record of when they started, what changed, and why you sought care when you did.', ['Write down when symptoms first appeared', 'Get checked once the pattern is clear enough to describe', 'Keep the timeline consistent across forms and conversations'], ['You wait a long time without documenting why symptoms were delayed']),
      m('Provider choice and follow-up affect both care and documentation', ['choose my own doctor'], 'You usually want a provider who can treat the actual issue and document it clearly. Follow-up instructions, referrals, and specialty care matter because they show the path of treatment over time.', ['Ask what follow-up care is expected', 'Keep referrals and imaging orders together', 'Make sure every visit notes the same injury story accurately'], ['The treatment path is scattered with no clear follow-up chain']),
      m('Treatment gaps caused by cost still need to be explained', ['stopped treatment because of cost'], 'If you paused care because of money, transportation, or confusion, explain the gap clearly and keep records of what happened. A gap is not fatal, but an unexplained gap can weaken both medical clarity and claim clarity.', ['Write down why the gap happened', 'Restart care in a way that reconnects the timeline', 'Keep bills, transportation, and scheduling proof if relevant'], ['You restart care later with no explanation of the break'])
    ]
  ),
  '/personal-injury/evidence-documents/': makeConfig(
    'Quick answer',
    'Evidence after an accident is not one pile of paperwork. The useful categories are scene proof, medical proof, financial proof, witness proof, and insurer communication. The goal is to preserve the basics early so the story does not get rebuilt later from memory.',
    'What evidence and documents matter most after an accident',
    'Use this page as a practical evidence checklist so you know what to save first, what not to send casually, and what you can still rebuild if something is missing.',
    ['Preserve scene photos, vehicle/property photos, and contact information early', 'Keep every medical note, imaging result, discharge paper, and bill', 'Separate insurer communication from your own record file', 'Save wage-loss and out-of-pocket proof as it appears', 'Do not send broad medical-record packages casually without understanding why'],
    'What makes evidence useful instead of messy',
    ['Evidence works best when grouped by type.', 'Medical proof and financial proof usually need separate tracking.', 'Good documentation is about timeline clarity as much as quantity.', 'You do not need every record in hand before talking to counsel.'],
    [
      m('Scene proof comes first: photos, damage, and basic facts', ['what evidence matters most','photos'], 'The first evidence bucket is scene proof: photos of vehicles or conditions, visible injuries, road or property conditions, and any basic identifying information that helps anchor what happened.', ['Save wide shots and close-ups', 'Keep date-stamped photos if possible', 'Store witness and police or incident details in one place'], ['You rely only on memory for the scene']),
      m('Medical proof builds the injury timeline', ['medical records','records','imaging','prescription','discharge'], 'The next bucket is medical proof: intake notes, discharge papers, imaging, prescriptions, referrals, and bills. These records matter because they show when symptoms were reported and how treatment developed.', ['Keep every discharge note and referral', 'Save imaging reports and prescription records', 'Track bills separately from clinical notes'], ['You have treatment but no organized record trail']),
      m('Do not send broad records to insurance casually', ['send medical records directly to insurance','send medical records','insurance'], 'Insurance requests can sound routine, but broad record sharing should be deliberate. Know what is being requested, why, and whether the request is narrower than the full chart.', ['Ask what specific records are being requested', 'Keep a copy of anything you send', 'Track the date and reason for every disclosure'], ['You send entire records packages without understanding the request']),
      m('You do not need every bill before talking to a lawyer', ['need every bill before talking to a lawyer','bill before talking to a lawyer','talking to a lawyer','bills'], 'You do not need a perfect folder before getting legal guidance. What matters early is enough proof to explain what happened, what treatment started, and what is still missing.', ['Organize what you already have', 'List what is still outstanding', 'Do not delay consultation only because the file is incomplete'], ['You wait for total perfection before asking useful questions'])
    ]
  ),
  '/personal-injury/situations/': makeConfig(
    'Quick answer',
    'You may be able to file a slip and fall claim at a grocery store, but the key issue is not only that you fell. The real issues are whether the store had a duty to keep the area reasonably safe, whether it knew or should have known about the condition, whether that condition caused the fall, and whether you suffered actual damages.',
    'Can You File a Slip and Fall Claim at a Grocery Store?',
    'Start with this eligibility checklist before you jump to broad “common situations” advice.',
    ['Duty of care', 'Notice', 'Causation', 'Damages', 'Check whether store video, incident reports, or witnesses may exist'],
    'What usually changes by situation',
    ['Different accident patterns create different proof problems.', 'Insurance path can matter as much as liability theory.', 'Urgency usually comes from injury severity, not panic.', 'The right next step is often more important than the perfect long-term plan on day one.'],
    [
      m('Can You File a Slip and Fall Claim at a Grocery Store?', ['slip and fall','grocery store','premises','private property'], 'You may be able to file a slip and fall claim at a grocery store, but the key issue is not only that you fell. The real issues are whether the store had a duty to keep the area reasonably safe, whether it knew or should have known about the condition, whether that condition caused the fall, and whether you suffered actual damages.', ['Duty of care', 'Notice', 'Causation', 'Damages'], ['No proof of what the unsafe condition was', 'No attention to how long the condition existed']),
      m('Do You Need a Lawyer After a Minor Accident?', ['minor accident','need a lawyer','severe car accident','parking lot crash','can i sue'], 'A minor accident question usually turns on injury clarity, fault disputes, insurance pressure, and whether the insurer is trying to close the claim before the full picture is known. What feels minor on day one does not always stay minor once treatment and wage loss are clearer.', ['Check whether injuries are still developing', 'Check whether fault is disputed', 'Check whether the insurer is pushing for quick statements or release'], ['You assume “minor” means the claim cannot get more complicated']),
      m('When Common Situations Turn Into Bigger Cases', ['hit-and-run','rideshare','truck','motorcycle','pedestrian','bike','uninsured','company vehicle'], 'Some situations become bigger cases because of the insurance path, the seriousness of injury, or the proof problem. Hit-and-run claims, uninsured-driver claims, rideshare claims, and serious truck or pedestrian cases often need a more structured next-step plan early.', ['Identify the insurance wrinkle that changes the path', 'Write down what proof already exists and what is missing', 'Escalate documentation and treatment tracking early in higher-stakes cases'], ['You treat a coverage-heavy or severe-injury case like a simple property-damage dispute']),
      m('Use the Situation Page to Choose the Next Move', ['what now','proof','next move','showed up later','later injuries','late symptoms'], 'The point of a situation page is to tell you what to do next: get treatment, gather proof, slow insurer contact, or compare lawyers. It is not a crystal ball for final case value.', ['Decide the next action before worrying about the final result', 'Use the local guide when the next step becomes choosing a lawyer', 'Keep the question list with you when you compare firms'], ['You are trying to estimate final case value before the basics are organized'])
    ]
  ),
};

function getPageShapeConfig(slug){
  return CONFIG[slug] || null;
}

module.exports = { CONFIG, getPageShapeConfig };
