#!/usr/bin/env node
'use strict';
const fs=require('fs');const path=require('path');const https=require('https');const L=require('./lib');
const conclusion=process.env.WORKFLOW_CONCLUSION||'unknown';const sha=process.env.WORKFLOW_HEAD_SHA||'';const runUrl=process.env.WORKFLOW_RUN_URL||'';const repo=process.env.GITHUB_REPOSITORY||'';const token=process.env.GITHUB_TOKEN||'';const health=L.readJson('data/search_intelligence/automation_health.json',{schema_version:'1.0',state:'UNPROVEN'});health.observed_at=new Date().toISOString();
if(conclusion==='success'){health.state='RECOVERED';health.last_validated_sha=sha;health.last_recovery_sha=sha;}else{health.state='RED';health.last_failure_sha=sha;health.failure_run_url=runUrl;}L.writeJson('data/search_intelligence/automation_health.json',health);
if(!token||!repo){console.log(`CI HEALTH ${health.state}: ${sha||'NO_SHA'} (no GitHub mutation: token/repo unavailable)`);process.exit(0);}
const [owner,name]=repo.split('/');const title='[Automation Health] Validate Repo CI RED';const body=`Exact SHA: ${sha}\nConclusion: ${conclusion}\nRun: ${runUrl}\n\nThis issue is managed by the CI health recovery loop. A later green exact-SHA run may close it.`;
function request(method,urlPath,payload){return new Promise((resolve,reject)=>{const data=payload?Buffer.from(JSON.stringify(payload)):null;const req=https.request({hostname:'api.github.com',path:urlPath,method,headers:{'User-Agent':'local-guides-ci-health','Authorization':`Bearer ${token}`,'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',...(data?{'Content-Type':'application/json','Content-Length':data.length}:{})}},res=>{let s='';res.on('data',d=>s+=d);res.on('end',()=>{if(res.statusCode>=200&&res.statusCode<300)resolve(s?JSON.parse(s):{});else reject(new Error(`${method} ${urlPath} -> ${res.statusCode}: ${s.slice(0,500)}`));});});req.on('error',reject);if(data)req.write(data);req.end();});}
(async()=>{const issues=await request('GET',`/repos/${owner}/${name}/issues?state=open&labels=automation-health&per_page=50`);const issue=issues.find(x=>x.title===title);if(conclusion==='success'){if(issue)await request('PATCH',`/repos/${owner}/${name}/issues/${issue.number}`,{state:'closed',body:`Recovered on exact SHA ${sha}.\nRun: ${runUrl}`});console.log(`CI HEALTH RECOVERED ${sha}`);return;}if(issue)await request('PATCH',`/repos/${owner}/${name}/issues/${issue.number}`,{body});else await request('POST',`/repos/${owner}/${name}/issues`,{title,body,labels:['automation-health']});console.log(`CI HEALTH RED ${sha}`);})().catch(e=>{console.error(e.stack||e.message);process.exit(1);});
