#!/usr/bin/env node
'use strict';
const fs=require('fs');const path=require('path');const L=require('./lib');
const {ROOT,readJson,writeJson,sha256,stableDate,stableTimestamp,normalizeQuery,routeToFile,exists,textFromHtml,loadContract,candidateStatusFromDiagnosis,verifyExternalObservation,verifyCitationEvent,addDays,safeJsonPatch,isProtected}=L;
function pickTargets(){
  const contract=loadContract();const admission=readJson('data/content/page_admission_registry.json');
  const verticals=['personal-injury','dentistry','trt','neuro','uscis-medical'];const pools=new Map(verticals.map(v=>[v,[]]));
  for(const p of admission.pages||[]){const q=String(p.primary_query||'').trim();if(p.publication_status!=='ADMITTED'||!pools.has(p.vertical)||!q||q.startsWith('/')||q.length<8||q.length>220)continue;const rendered=routeToFile(p.path);if(!exists(rendered))continue;const html=fs.readFileSync(path.join(ROOT,rendered),'utf8');const score=(/data-direct-answer="true"/i.test(html)?30:0)+(/<table\b/i.test(html)?10:0)+(/application\/ld\+json/i.test(html)?10:0)+(p.source_owner==='VELOCITY_CONTENT'?15:0)+(p.required_sources?.length?10:0)+(p.page_type?.toLowerCase().includes('community')?-15:0);pools.get(p.vertical).push({p,q,score});}
  const selected=[];for(const v of verticals){const arr=pools.get(v).sort((a,b)=>b.score-a.score||a.q.localeCompare(b.q)||a.p.path.localeCompare(b.p.path));for(const x of arr.slice(0,48))selected.push(x);}
  if(selected.length!==contract.target_query_count)throw new Error(`TARGET_QUERY_COUNT:${selected.length}!=${contract.target_query_count}`);
  const targets=selected.map(({p,q},i)=>({query_id:`Q-${sha256(`${normalizeQuery(q)}|${p.path}`).slice(0,16).toUpperCase()}`,query:q,normalized_query:normalizeQuery(q),owner_route:p.path,vertical:p.vertical,page_type:p.page_type,source_owner:p.source_owner,source_file:p.source_file,required_sources:p.required_sources||[],sensitivity_profile:p.sensitivity_profile||'general',priority_rank:i+1,ownership_status:'OWNED',admission_status:p.publication_status}));
  const out={schema_version:'1.0',generated_at:stableTimestamp(),count:targets.length,ownership_rule:'Exactly one admitted canonical owner route per monitored query.',targets};writeJson('data/search_intelligence/target_query_set.json',out);return out;
}
function buildAgentBridge(){
  const contract=loadContract();const dir=path.join(ROOT,'data/report_fixes/normalized_agent_runs');const files=fs.readdirSync(dir).filter(f=>f.endsWith('.json')).sort().reverse();const seen=new Set(),signals=[];
  for(const f of files){const d=JSON.parse(fs.readFileSync(path.join(dir,f),'utf8'));for(const r of d.records||[]){const key=r.source_record_canonical_key||r.source_record_id||r.id;if(!key||seen.has(key))continue;seen.add(key);signals.push({signal_id:r.id||key,source_record_id:r.source_record_id||null,source_record_canonical_key:r.source_record_canonical_key||null,source_file:`data/report_fixes/normalized_agent_runs/${f}`,run_date:r.run_date||f.slice(0,10),vertical:r.vertical||null,query:r.query||null,normalized_query:normalizeQuery(r.query),intended_winner_path:r.intended_winner_path||r.intended_winner_page||null,fix_type:r.fix_type||null,action_tier:r.action_tier||null,recommendation:r.recommendation||r.recommendation_fields?.raw||null,read_only:true});if(signals.length>=contract.agent_signal_limit)break;}if(signals.length>=contract.agent_signal_limit)break;}
  const out={schema_version:'1.0',generated_at:stableTimestamp(),count:signals.length,source_mode:'READ_ONLY_AGENT_OUTPUTS',mutation_authority:false,signals};writeJson('data/search_intelligence/agent_signal_bridge.json',out);return out;
}
function buildProviderTruth(){
  const providers={gsc:{state:'NOT_CONFIGURED',evidence:[]},bing:{state:'NOT_CONFIGURED',evidence:[]},live_search:{state:'INCONCLUSIVE',evidence:[]}};
  function importEvidence(envName,key){const rel=process.env[envName];if(!rel)return;const p=path.isAbsolute(rel)?rel:path.join(ROOT,rel);if(!fs.existsSync(p)){providers[key]={state:'ERROR',evidence:[],error:'configured evidence file missing'};return;}const d=JSON.parse(fs.readFileSync(p,'utf8'));const ev=Array.isArray(d)?d:(d.events||d.observations||[]);providers[key]={state:'CONFIGURED',evidence:ev.filter(verifyExternalObservation),rejected_count:ev.filter(e=>!verifyExternalObservation(e)).length};}
  importEvidence('GSC_TRUTH_FILE','gsc');importEvidence('BING_TRUTH_FILE','bing');importEvidence('LIVE_SEARCH_OBSERVATIONS_FILE','live_search');
  const snapshot={schema_version:'1.0',generated_at:stableTimestamp(),truth_rule:'Provider absence is NOT_CONFIGURED/INCONCLUSIVE, never PASS or FAIL unless the operation requires that provider.',providers};
  writeJson('data/search_intelligence/provider_truth_snapshot.json',snapshot);writeJson('data/search_intelligence/gsc_truth.json',{schema_version:'1.0',generated_at:stableTimestamp(),provider:'GSC',...providers.gsc});writeJson('data/search_intelligence/live_search_observations.json',{schema_version:'1.0',generated_at:stableTimestamp(),provider:'LIVE_SEARCH',...providers.live_search});return snapshot;
}
function diagnose(){
  const targets=readJson('data/search_intelligence/target_query_set.json').targets;const bridge=readJson('data/search_intelligence/agent_signal_bridge.json',{signals:[]});const provider=readJson('data/search_intelligence/provider_truth_snapshot.json');let sitemap=fs.readFileSync(path.join(ROOT,'sitemap.xml'),'utf8');const sitemapDir=path.join(ROOT,'sitemaps');if(fs.existsSync(sitemapDir))for(const f of fs.readdirSync(sitemapDir).filter(x=>x.endsWith('.xml')))sitemap+='\n'+fs.readFileSync(path.join(sitemapDir,f),'utf8');const claims=readJson('data/evidence/claim_registry.json',{claims:[]});const claimRoutes=new Set((claims.claims||claims.items||[]).map(c=>c.page_route).filter(Boolean));
  const signalsByRoute=new Map();for(const s of bridge.signals||[]){let r=s.intended_winner_path||'';if(r&&!r.startsWith('/'))r='/'+r;if(r.endsWith('index.html'))r='/'+r.replace(/^\//,'').replace(/index\.html$/,'');if(r&&!r.endsWith('/')&&!r.endsWith('.html'))r+='/';if(r)(signalsByRoute.get(r)||signalsByRoute.set(r,[]).get(r)).push(s);}
  const rows=[];
  for(const t of targets){const file=routeToFile(t.owner_route);const html=fs.readFileSync(path.join(ROOT,file),'utf8');const text=textFromHtml(html);const title=/<title>[^<]{3,}<\/title>/i.test(html);const h1=/<h1\b[^>]*>[^<]{2,}<\/h1>/i.test(html);const canonical=/<link\b[^>]*rel=["']canonical["'][^>]*href=/i.test(html)||/<link\b[^>]*href=[^>]*rel=["']canonical["']/i.test(html);const noindex=/<meta\b[^>]*name=["']robots["'][^>]*noindex/i.test(html);const direct=/data-direct-answer=["']true["']/i.test(html)||/class=["'][^"']*answer-box/i.test(html);const structured=/<table\b/i.test(html)||/<ul\b/i.test(html)||/<ol\b/i.test(html);const schema=/application\/ld\+json/i.test(html);const sourceBlock=/data-primary-sources=["']true["']/i.test(html)||/Primary sources/i.test(html);const publisher=/The Industry Guides/i.test(html);const internalLinks=(html.match(/href=["']\//g)||[]).length;const sitemapOk=sitemap.includes(t.owner_route)||sitemap.includes(t.owner_route.replace(/\/$/,''));const placeholder=/\b(lorem ipsum|todo|tbd|placeholder)\b/i.test(text);const regulated=['trt','uscis-medical','neuro'].includes(t.vertical)||t.sensitivity_profile!=='general';const sources=(t.required_sources||[]).length;const agentSignals=signalsByRoute.get(t.owner_route)||[];
    const material=[];if(!canonical)material.push('missing_canonical');if(!title)material.push('missing_title');if(!h1)material.push('missing_h1');if(noindex)material.push('unexpected_noindex');if(!sitemapOk)material.push('sitemap_missing');if(placeholder)material.push('placeholder_text');
    let repair_type=null;if(material.includes('missing_canonical'))repair_type='CANONICAL_LINK';else if(material.includes('sitemap_missing'))repair_type='SITEMAP_CONSISTENCY';else if(material.includes('missing_title'))repair_type='METADATA_DESCRIPTION';
    rows.push({query_id:t.query_id,query:t.query,owner_route:t.owner_route,vertical:t.vertical,material_state:material.length?'DEFECT':'HEALTHY',material_findings:material,repair_type,regulated_claim_risk:Boolean(regulated&&repair_type&&repair_type!=='CANONICAL_LINK'&&repair_type!=='SITEMAP_CONSISTENCY'),seo:{canonical,title,h1,sitemap:sitemapOk,indexable:!noindex,internal_links:internalLinks},aeo:{direct_answer:direct,structured_answer:structured,word_count:text.split(/\s+/).filter(Boolean).length,answer_completeness:direct&&structured?'STRONG':direct?'ADEQUATE':'OBSERVE'},geo:{schema,publisher_identity:publisher,source_block:sourceBlock,required_source_count:sources,claim_registry_coverage:claimRoutes.has(t.owner_route)},content_quality:{placeholder_free:!placeholder,thin:text.split(/\s+/).filter(Boolean).length<180},external_evidence_state:Object.values(provider.providers).some(p=>p.state==='CONFIGURED')?'OBSERVED_PROVIDER_DATA_AVAILABLE':'INCONCLUSIVE',agent_signal_count:agentSignals.length});}
  const out={schema_version:'1.0',generated_at:stableTimestamp(),count:rows.length,diagnoses:rows};writeJson('data/search_intelligence/search_diagnosis.json',out);return out;
}
function buildCandidates(){
  const targets=new Map(readJson('data/search_intelligence/target_query_set.json').targets.map(t=>[t.query_id,t]));const diagnoses=readJson('data/search_intelligence/search_diagnosis.json').diagnoses;const existing=readJson('data/search_intelligence/repair_receipts.json',{repairs:[]});const contract=loadContract();const candidates=[];
  for(const d of diagnoses){const status=candidateStatusFromDiagnosis(d);if(!status)continue;const t=targets.get(d.query_id);const prior=[...(existing.repairs||[])].filter(r=>r.query_id===d.query_id&&r.applied_at).sort((a,b)=>String(b.applied_at).localeCompare(String(a.applied_at)))[0];const cooldown_until=prior?addDays(prior.applied_at,contract.default_repair_cooldown_days):null;const cooldown_active=Boolean(cooldown_until&&stableDate()<cooldown_until);candidates.push({repair_id:`R-${sha256(`${d.query_id}|${d.repair_type}|${d.owner_route}`).slice(0,16).toUpperCase()}`,query_id:d.query_id,target_route:d.owner_route,source_file:t.source_file,diagnosis:d.material_findings,repair_type:d.repair_type,before_evidence:{rendered_file:routeToFile(d.owner_route),rendered_sha256:L.fileSha(routeToFile(d.owner_route))},source_basis:t.required_sources||[],risk_class:d.regulated_claim_risk?'REVIEW':'LOW',allowed_mutation:t.source_file,expected_outcome:'Resolve material local structural defect without changing page ownership or publishing cadence.',cooldown_days:contract.default_repair_cooldown_days,cooldown_until,cooldown_active,status:cooldown_active?'COOLDOWN':status,patch:null});}
  const out={schema_version:'1.0',generated_at:stableTimestamp(),count:candidates.length,preference:'REPAIR_EXISTING_PAGE',new_url_authority:false,candidates};writeJson('data/search_intelligence/repair_candidates.json',out);return out;
}
function applyRepairs(){
  const payload=readJson('data/search_intelligence/repair_candidates.json',{candidates:[]});const receipts=readJson('data/search_intelligence/repair_receipts.json',{schema_version:'1.0',repairs:[]});const retest=readJson('data/search_intelligence/retest_queue.json',{schema_version:'1.0',items:[]});let applied=0;
  for(const c of payload.candidates||[]){if(c.status!=='READY_AUTO_REPAIR'||c.cooldown_active||!c.patch)continue;if(isProtected(c.source_file))throw new Error(`PROTECTED_PATH:${c.source_file}`);const beforeBytes=fs.readFileSync(path.join(ROOT,c.source_file));const snapshotRel=`data/search_intelligence/rollback_snapshots/${c.repair_id}.json`;writeJson(snapshotRel,{schema_version:'1.0',repair_id:c.repair_id,source_file:c.source_file,before_sha256:sha256(beforeBytes),before_base64:beforeBytes.toString('base64')});const m=safeJsonPatch({source_file:c.source_file,route:c.target_route,patch:c.patch});if(!m.changed)throw new Error(`REPAIR_APPLIED_WITHOUT_MUTATION:${c.repair_id}`);const receipt={repair_id:c.repair_id,query_id:c.query_id,target_route:c.target_route,source_file:c.source_file,status:'APPLIED',applied_at:stableDate(),...m,rollback_snapshot:snapshotRel,rollback_eligible:true};receipts.repairs.push(receipt);retest.items.push({repair_id:c.repair_id,query_id:c.query_id,target_route:c.target_route,before_evidence:c.before_evidence,applied_at:stableDate(),retest_due_date:addDays(stableDate(),loadContract().default_repair_cooldown_days),status:'PENDING_EXTERNAL_RETEST'});applied++;}
  receipts.generated_at=stableTimestamp();retest.generated_at=stableTimestamp();writeJson('data/search_intelligence/repair_receipts.json',receipts);writeJson('data/search_intelligence/retest_queue.json',retest);return {applied};
}
function evaluateRetests(){
  const queue=readJson('data/search_intelligence/retest_queue.json',{items:[]});const obs=readJson('data/search_intelligence/live_search_observations.json',{evidence:[]});const outcomes=readJson('data/search_intelligence/retest_outcomes.json',{schema_version:'1.0',outcomes:[]});const byRepair=new Map((outcomes.outcomes||[]).map(o=>[o.repair_id,o]));for(const q of queue.items||[]){if(stableDate()<q.retest_due_date)continue;const matches=(obs.evidence||[]).filter(e=>e.owner_route===q.target_route&&verifyExternalObservation(e));const before=matches.filter(e=>String(e.observed_at).slice(0,10)<=q.applied_at).sort((a,b)=>String(b.observed_at).localeCompare(String(a.observed_at)))[0];const after=matches.filter(e=>String(e.observed_at).slice(0,10)>=q.retest_due_date).sort((a,b)=>String(b.observed_at).localeCompare(String(a.observed_at)))[0];let outcome='INCONCLUSIVE';if(before&&after&&Number.isFinite(before.metric)&&Number.isFinite(after.metric)){outcome=after.metric>before.metric?'IMPROVED':after.metric<before.metric?'REGRESSED':'UNCHANGED';}byRepair.set(q.repair_id,{repair_id:q.repair_id,query_id:q.query_id,target_route:q.target_route,outcome,before_external_evidence:before||null,after_external_evidence:after||null,evaluated_at:stableDate()});}
  const out={schema_version:'1.0',generated_at:stableTimestamp(),outcomes:[...byRepair.values()]};writeJson('data/search_intelligence/retest_outcomes.json',out);return out;
}
function citations(){let existing=readJson('data/search_intelligence/verified_external_citations.json',{schema_version:'1.0',events:[]});existing.events=(existing.events||[]).filter(verifyCitationEvent);existing.count=existing.events.length;existing.generated_at=stableTimestamp();existing.truth_rule='Only events with provider, timestamp, prompt/query, surfaced URL, cited URL, and evidence reference count.';writeJson('data/search_intelligence/verified_external_citations.json',existing);return existing;}
function feedback(){const outcomes=readJson('data/search_intelligence/retest_outcomes.json',{outcomes:[]});const cites=citations();const bridge=readJson('data/search_intelligence/agent_signal_bridge.json',{signals:[]});const counts={IMPROVED:0,UNCHANGED:0,REGRESSED:0,INCONCLUSIVE:0};for(const o of outcomes.outcomes||[])counts[o.outcome]=(counts[o.outcome]||0)+1;const out={schema_version:'1.0',generated_at:stableTimestamp(),verified_external_citations:cites.count,retest_outcomes:counts,agent_signals_read_only:(bridge.signals||[]).length,feedback_actions:{refresh_priority:counts.REGRESSED>0?'RAISE_REGRESSED':'HOLD',query_priority:cites.count>0?'WEIGHT_VERIFIED_YIELD':'NO_EXTERNAL_YIELD_SIGNAL',internal_link_priority:'MAY_ADJUST_WITHIN_EXISTING_ADMITTED_ROUTES',vertical_focus:'MAY_ADJUST_FROM_VERIFIED_EVIDENCE_ONLY'},cannot_override:['canonical rules','regulated-content gates','Agent Run provenance','page admission','duplicate checks','publishing governance','velocity ceiling']};writeJson('data/search_intelligence/authority_feedback.json',out);return out;}
function scorecard(){const t=readJson('data/search_intelligence/target_query_set.json').targets;const d=new Map(readJson('data/search_intelligence/search_diagnosis.json').diagnoses.map(x=>[x.query_id,x]));const outcomes=readJson('data/search_intelligence/retest_outcomes.json',{outcomes:[]});const byQ=new Map((outcomes.outcomes||[]).map(o=>[o.query_id,o.outcome]));const rows=t.map(x=>{const y=d.get(x.query_id);return {query_id:x.query_id,query:x.query,route:x.owner_route,vertical:x.vertical,SEO:y?.seo||null,AEO:y?.aeo||null,GEO:y?.geo||null,CONTENT_QUALITY:y?.content_quality||null,EXTERNAL_EVIDENCE:y?.external_evidence_state||'INCONCLUSIVE',AGENT_SIGNAL:y?.agent_signal_count||0,RETEST_STATUS:byQ.get(x.query_id)||'NO_RETEST_DATA_YET'};});const out={schema_version:'1.0',generated_at:stableTimestamp(),dimensions:['SEO','AEO','GEO','CONTENT_QUALITY','EXTERNAL_EVIDENCE','AGENT_SIGNAL','RETEST_STATUS'],count:rows.length,rows};writeJson('data/search_intelligence/operator_scorecard.json',out);return out;}
function initEmpty(){for(const [rel,value] of Object.entries({'data/search_intelligence/repair_receipts.json':{schema_version:'1.0',repairs:[]},'data/search_intelligence/retest_queue.json':{schema_version:'1.0',items:[]},'data/search_intelligence/retest_outcomes.json':{schema_version:'1.0',outcomes:[]},'data/search_intelligence/regression_ledger.json':{schema_version:'1.0',events:[]},'data/search_intelligence/verified_external_citations.json':{schema_version:'1.0',events:[]},'data/search_intelligence/automation_health.json':{schema_version:'1.0',state:'UNPROVEN',last_validated_sha:null,last_failure_sha:null,last_recovery_sha:null,truth_rule:'CI health changes only from observed exact-SHA workflow results.'}}))if(!exists(rel))writeJson(rel,value);}
function full({apply=false}={}){initEmpty();pickTargets();buildAgentBridge();buildProviderTruth();diagnose();buildCandidates();if(apply)applyRepairs();evaluateRetests();feedback();scorecard();return {targets:readJson('data/search_intelligence/target_query_set.json').count,agent_signals:readJson('data/search_intelligence/agent_signal_bridge.json').count,candidates:readJson('data/search_intelligence/repair_candidates.json').count};}
const cmd=process.argv[2]||'full';initEmpty();const map={targets:pickTargets,agent:buildAgentBridge,providers:buildProviderTruth,diagnose,candidates:buildCandidates,apply:applyRepairs,retest:evaluateRetests,feedback,scorecard,full:()=>full({apply:process.argv.includes('--apply')})};if(!map[cmd])throw new Error(`Unknown command ${cmd}`);const r=map[cmd]();console.log(`SEARCH INTELLIGENCE ${cmd.toUpperCase()} PASS ${JSON.stringify(r&&typeof r==='object'?r:{})}`);
