'use strict';
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const ROOT=path.resolve(__dirname,'../..');
const REGISTRY_PATH=path.join(ROOT,'_validation_registry.json');
function readRegistry(){return JSON.parse(fs.readFileSync(REGISTRY_PATH,'utf8'));}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]));return value;}
function registryHash(reg){return crypto.createHash('sha256').update(JSON.stringify(stable(reg))).digest('hex');}
function norm(p){return String(p||'').replace(/\\/g,'/').replace(/^\.\//,'');}
function exists(rel){return fs.existsSync(path.join(ROOT,rel));}
function walk(abs,out=[]){if(!fs.existsSync(abs))return out;const st=fs.statSync(abs);if(st.isFile()){out.push(abs);return out;}for(const ent of fs.readdirSync(abs,{withFileTypes:true})){const p=path.join(abs,ent.name);if(ent.isDirectory())walk(p,out);else out.push(p);}return out;}
function fileSha(abs){return crypto.createHash('sha256').update(fs.readFileSync(abs)).digest('hex');}
function sourceSnapshot(reg){const snap=new Map();for(const rel of reg.lineage_policy?.source_roots||[]){const abs=path.join(ROOT,rel);for(const file of walk(abs)){const r=norm(path.relative(ROOT,file));if(/(^|\/)node_modules\//.test(r))continue;snap.set(r,fileSha(file));}}return snap;}
function mutationDiff(before,after){const keys=new Set([...before.keys(),...after.keys()]);const changed=[];for(const key of keys)if(before.get(key)!==after.get(key))changed.push(key);return changed.sort();}
function globRegex(glob){const g=norm(glob);let x='';for(let i=0;i<g.length;i++){const c=g[i];if(c==='*'&&g[i+1]==='*'){x+='.*';i++;}else if(c==='*')x+='[^/]*';else if(c==='?')x+='.';else x+=c.replace(/[.+^${}()|[\]\\]/g,'\\$&');}return new RegExp(`^${x}$`);}
function allowedPath(rel,patterns){return (patterns||[]).some(p=>globRegex(p).test(norm(rel)));}
function dependencyClosure(reg,ids){const byId=new Map(reg.validators.map(v=>[v.id,v]));const out=new Set();function add(id,trail=[]){if(out.has(id))return;const v=byId.get(id);if(!v)throw new Error(`Unknown dependency ${id} required by ${trail.at(-1)||'selection'}`);if(trail.includes(id))throw new Error(`Dependency cycle: ${[...trail,id].join(' -> ')}`);for(const dep of v.depends_on||[])add(dep,[...trail,id]);out.add(id);}for(const id of ids)add(id);return [...out];}
function topologicalValidators(reg,ids){const byId=new Map(reg.validators.map(v=>[v.id,v]));const closure=new Set(dependencyClosure(reg,ids));const indegree=new Map([...closure].map(id=>[id,0]));const edges=new Map([...closure].map(id=>[id,[]]));for(const id of closure){for(const dep of byId.get(id).depends_on||[]){if(!closure.has(dep))continue;indegree.set(id,indegree.get(id)+1);edges.get(dep).push(id);}}
 const tierNum=v=>Number(String(v.tier||'').match(/\d+/)?.[0]||99);const ready=[...closure].filter(id=>indegree.get(id)===0).sort((a,b)=>tierNum(byId.get(a))-tierNum(byId.get(b))||a.localeCompare(b));const ordered=[];while(ready.length){const id=ready.shift();ordered.push(byId.get(id));for(const next of edges.get(id)){indegree.set(next,indegree.get(next)-1);if(indegree.get(next)===0){ready.push(next);ready.sort((a,b)=>tierNum(byId.get(a))-tierNum(byId.get(b))||a.localeCompare(b));}}}if(ordered.length!==closure.size)throw new Error('Dependency graph contains a cycle');return ordered;}
function buildMatrix(reg){
 const validators=reg.validators.map(v=>({id:v.id,title:v.title,status:v.status,severity:v.severity,tier:v.tier,scope:v.scope,profiles:v.profiles,path:v.path,command:v.command,depends_on:v.depends_on||[],requires_files:v.requires_files||[],prepare_commands:v.prepare_commands||[],prepare_produces_files:v.prepare_produces_files||[],prepare_mutates_files:v.prepare_mutates_files||[],produces_files:v.produces_files||[],mutates_files:v.mutates_files||[],enforce_no_source_mutation:v.enforce_no_source_mutation!==false,risk_prevented:v.risk_prevented,default_behavior:v.scope==='LOCAL_ONLY'?'DEFERRED_LOCAL_ONLY':(v.severity==='HARD_FAIL'?'BLOCK_RELEASE':v.severity==='STRONG_WARNING'?'WARN_CONTINUE':'RECORD_CONTINUE'),strict_behavior:v.scope==='LOCAL_ONLY'?'RUN_WHEN_LOCAL':(['HARD_FAIL','STRONG_WARNING'].includes(v.severity)?'BLOCK_RELEASE':'RECORD_CONTINUE'),replacement_ids:v.replacement_ids||[],retirement_reason:v.retirement_reason||null}));
 const bySeverity={};for(const s of Object.keys(reg.severity_definitions))bySeverity[s]=validators.filter(v=>v.severity===s);const byTier={};for(const v of validators)(byTier[v.tier]??=[]).push(v);const counts={total:validators.length,active:validators.filter(v=>v.status==='ACTIVE').length,on_demand:validators.filter(v=>v.status==='ON_DEMAND').length,retired:validators.filter(v=>v.status==='RETIRED').length,local_only:validators.filter(v=>v.scope==='LOCAL_ONLY').length};for(const s of Object.keys(bySeverity))counts[s.toLowerCase()]=bySeverity[s].length;
 return {schema_version:'3.0',generated_from:'_validation_registry.json',registry_sha256:registryHash(reg),authority:'Generated executable projection. Edit _validation_registry.json, then run npm run validation:matrix.',lineage_policy:reg.lineage_policy,severity_definitions:reg.severity_definitions,scope_definitions:reg.scope_definitions,counts,profiles:Object.fromEntries(Object.entries(reg.profiles).map(([name,p])=>[name,{...p,validator_ids:validators.filter(v=>v.profiles.includes(name)&&v.status!=='RETIRED').map(v=>v.id),execution_order:topologicalValidators(reg,validators.filter(v=>v.profiles.includes(name)&&v.status!=='RETIRED').map(v=>v.id)).map(v=>v.id)}])),dependency_edges:validators.flatMap(v=>(v.depends_on||[]).map(dep=>({from:dep,to:v.id}))),by_severity:bySeverity,by_tier:byTier,not_applicable:[{lane:'authentication',reason:'public static site'},{lane:'roles',reason:'no authenticated roles'},{lane:'provider mutation',reason:'no provider mutation surface'},{lane:'cleanup',reason:'no runtime persistence cleanup'}]};
}
module.exports={ROOT,REGISTRY_PATH,readRegistry,buildMatrix,registryHash,stable,norm,exists,sourceSnapshot,mutationDiff,allowedPath,dependencyClosure,topologicalValidators};
