#!/usr/bin/env node
'use strict';
const fs=require('fs');const path=require('path');const cp=require('child_process');
const {ROOT,readRegistry,topologicalValidators,sourceSnapshot,mutationDiff,allowedPath,exists,runtimeDirName}=require('./registry_lib');const {classifyResult}=require('./policy');const {emitFailureLegibility}=require('./failure_legibility');
function parseArgs(argv){const out={profiles:[],ids:[],collectAll:false,strictWarnings:false,includeLocal:false,list:false,dryRun:false,shard:null};for(let i=0;i<argv.length;i++){const a=argv[i];if(a==='--profile')out.profiles.push(argv[++i]);else if(a==='--id')out.ids.push(argv[++i]);else if(a==='--collect-all')out.collectAll=true;else if(a==='--strict-warnings')out.strictWarnings=true;else if(a==='--include-local')out.includeLocal=true;else if(a==='--list')out.list=true;else if(a==='--dry-run')out.dryRun=true;else if(a==='--shard')out.shard=argv[++i];else if(a==='--help'){console.log('Usage: node scripts/validation/run_validation_registry.js [--profile NAME] [--id ID] [--collect-all] [--strict-warnings] [--include-local] [--list] [--dry-run] [--shard I/N]');process.exit(0);}else throw new Error(`Unknown argument: ${a}`);}if(!out.profiles.length&&!out.ids.length&&!out.list)out.profiles=['core'];return out;}
function stableTimestamp(){if(process.env.VALIDATION_TIMESTAMP)return process.env.VALIDATION_TIMESTAMP;try{const runs=JSON.parse(fs.readFileSync(path.join(ROOT,'data/citation_velocity/runs.json'),'utf8'));const date=runs.current_through||runs.runs?.map(r=>r.date).filter(Boolean).sort().at(-1);if(date)return `${date}T00:00:00.000Z`;}catch{}return '1970-01-01T00:00:00.000Z';}
function detectWarning(v,text){return (v.warning_patterns||[]).some(p=>new RegExp(p,'i').test(text));}
function selectedValidators(reg,args){const unknownProfiles=args.profiles.filter(p=>!reg.profiles[p]);if(unknownProfiles.length)throw new Error(`Unknown profile(s): ${unknownProfiles.join(', ')}`);const byId=new Map(reg.validators.map(v=>[v.id,v]));const unknownIds=args.ids.filter(id=>!byId.has(id));if(unknownIds.length)throw new Error(`Unknown validator id(s): ${unknownIds.join(', ')}`);const ids=[];for(const p of args.profiles)for(const v of reg.validators)if(v.profiles.includes(p)&&v.status!=='RETIRED')ids.push(v.id);for(const id of args.ids){const v=byId.get(id);if(v.status==='RETIRED')throw new Error(`Validator ${id} is RETIRED. Use ${(v.replacement_ids||[]).join(', ')||'registered replacement'}.`);ids.push(id);}return topologicalValidators(reg,[...new Set(ids)]);}
function runCommand(command,timeout,logFile){const r=cp.spawnSync(command,{cwd:ROOT,shell:true,encoding:'utf8',timeout:timeout*1000,maxBuffer:80*1024*1024,env:{...process.env,NODE_OPTIONS:process.env.NODE_OPTIONS||'--max-old-space-size=3072'}});fs.appendFileSync(logFile,`$ ${command}\n\nSTDOUT\n${r.stdout||''}\nSTDERR\n${r.stderr||''}\n`);if(r.stdout)process.stdout.write(r.stdout);if(r.stderr)process.stderr.write(r.stderr);return r;}
// SHARDING. The release profile is ~180 validators and 7-11 minutes of wall time on
// one runner, of which two validators (the clock-independence pair, which re-run other
// validators under two clocks) are more than half. A merge gate that slow taxes every
// fix, so Validate Repo runs the profile as N parallel shards and one aggregate job
// (scripts/validation/merge_validation_shards.js) that proves every validator of the
// profile was assigned exactly once and passed. Assignment is longest-processing-time
// greedy over MEASURED durations - the committed validation-summary-release.json from
// the last full run, falling back to the registry's estimated_runtime_seconds - so it is
// the same on every shard of one commit (all read the same committed file). Each shard
// runs its assigned validators plus their dependency closure, in dependency order, so a
// validator never runs before the evidence it requires exists.
// Weights come from the committed validation-summary-release.json. A SHARDED run
// writes only its own validation-summary-shard-I-of-N.json - never the profile
// summary - so that file is the same bytes on every shard of one commit, and shards
// that agree on weights agree on assignment. (Shards that disagreed would assign a
// validator twice or not at all; merge_validation_shards.js fails on either.)
function shardWeights(reg){const byId=new Map(reg.validators.map(v=>[v.id,Math.max(1000,(Number(v.estimated_runtime_seconds)||1)*1000)]));let source='registry:estimated_runtime_seconds';for(const rel of ['artifacts/validation/validation-summary-release.json','artifacts/validation/validation-summary.json']){let text=null;try{text=fs.readFileSync(path.join(ROOT,rel),'utf8');}catch{continue;}try{const s=JSON.parse(text);if(s.shard)continue;let n=0;for(const r of s.results||[]){if(r&&r.id&&Number(r.duration_ms)>0&&byId.has(r.id)){byId.set(r.id,Math.max(1000,Number(r.duration_ms)));n++;}}if(n){source=`${rel} (${n} measured)`;break;}}catch{}}return {byId,source};}
function shardValidators(reg,validators,spec){const m=String(spec||'').match(/^(\d+)\/(\d+)$/);if(!m)throw new Error(`Invalid --shard "${spec}": expected I/N with 0 <= I < N`);const index=Number(m[1]),count=Number(m[2]);if(!(count>=1)||!(index>=0)||index>=count)throw new Error(`Invalid --shard "${spec}": expected 0 <= I < N`);const {byId,source}=shardWeights(reg);const weighted=validators.map(v=>({v,w:byId.get(v.id)||1000})).sort((a,b)=>b.w-a.w||a.v.id.localeCompare(b.v.id));const loads=new Array(count).fill(0);const assigned=Array.from({length:count},()=>[]);for(const {v,w} of weighted){let best=0;for(let i=1;i<count;i++)if(loads[i]<loads[best])best=i;assigned[best].push(v.id);loads[best]+=w;}const mine=assigned[index];const ordered=topologicalValidators(reg,mine);const heaviest=weighted.find(x=>mine.includes(x.v.id))||{v:{id:'none'},w:0};return {index,count,assigned_ids:mine,ordered,weights_source:source,assigned_weight_ms:loads[index],loads_ms:loads,heaviest:{id:heaviest.v.id,weight_ms:heaviest.w}};}
function main(){const args=parseArgs(process.argv.slice(2));const reg=readRegistry();if(args.list){for(const v of reg.validators)console.log([v.id,v.status,v.severity,v.scope,v.tier,(v.depends_on||[]).join('|'),v.profiles.join(','),v.path].join('\t'));return;}for(const p of args.profiles){if(reg.profiles[p]?.collect_all)args.collectAll=true;if(reg.profiles[p]?.promote_strong_warnings)args.strictWarnings=true;}let validators=selectedValidators(reg,args);if(!validators.length)throw new Error('No validators selected.');const profileValidatorIds=validators.map(v=>v.id);let shard=null;if(args.shard){shard=shardValidators(reg,validators,args.shard);validators=shard.ordered;console.log(`VALIDATION SHARD ${shard.index}/${shard.count}: ${shard.assigned_ids.length} assigned (${Math.round(shard.assigned_weight_ms/1000)}s by ${shard.weights_source}), ${validators.length} to run including dependencies; heaviest ${shard.heaviest.id} ${Math.round(shard.heaviest.weight_ms/1000)}s`);}const runtimeDir=path.join(ROOT,'artifacts/validation/runtime',runtimeDirName());fs.mkdirSync(runtimeDir,{recursive:true});const results=[];let blocked=false;const prepared=new Set();let mutationState=args.dryRun?null:sourceSnapshot(reg);console.log(`VALIDATION REGISTRY RUN: ${validators.length} validator(s) | profiles=${args.profiles.join(',')||'none'} | dependency_order=ON | prerequisites=ON | mutation_guard=ON`);console.log(`RUNTIME LOGS: ${path.relative(ROOT,runtimeDir).replace(/\\/g,'/')} (gitignored, local to this run)`);
 for(const v of validators){if(blocked&&!args.collectAll){results.push({id:v.id,status:'NOT_RUN_AFTER_BLOCK',severity:v.severity});continue;}if(v.scope==='LOCAL_ONLY'&&!args.includeLocal&&!args.profiles.includes('local')){console.log(`DEFERRED ${v.id} (LOCAL_ONLY)`);results.push({id:v.id,status:'DEFERRED_LOCAL_ONLY',severity:v.severity,scope:v.scope});continue;}console.log(`\n[${v.tier}] ${v.id} — ${v.title}`);const logFile=path.join(runtimeDir,`${v.id}.log`);if(args.dryRun){console.log(`DRY RUN: ${(v.prepare_commands||[]).join(' && ')} ${v.command}`);results.push({id:v.id,status:'DRY_RUN',severity:v.severity});continue;}
  let prereqMissing=(v.requires_files||[]).filter(rel=>!exists(rel));const prepareResults=[];if(prereqMissing.length){for(const command of v.prepare_commands||[]){if(prepared.has(command))continue;console.log(`PREPARE ${v.id}: ${command}`);const pr=runCommand(command,v.timeout_seconds||300,logFile);prepareResults.push({command,exit_code:pr.status,signal:pr.signal||null});if(pr.status!==0){blocked=true;results.push({id:v.id,status:'PREPARE_FAILED',severity:v.severity,blocks_release:true,missing_files:prereqMissing,prepare_results:prepareResults,log:path.relative(ROOT,logFile).replace(/\\/g,'/')});break;}prepared.add(command);}if(blocked&&!args.collectAll)continue;prereqMissing=(v.requires_files||[]).filter(rel=>!exists(rel));if(prereqMissing.length){blocked=true;console.error(`BLOCKING RESULT: ${v.id} => PREREQUISITE_MISSING ${prereqMissing.join(', ')}`);results.push({id:v.id,status:'PREREQUISITE_MISSING',severity:v.severity,blocks_release:true,missing_files:prereqMissing,prepare_results:prepareResults,log:path.relative(ROOT,logFile).replace(/\\/g,'/')});continue;}}
  const enforceMutation=v.enforce_no_source_mutation!==false;const before=mutationState;const started=Date.now();const r=runCommand(v.command,v.timeout_seconds||300,logFile);const after=sourceSnapshot(reg,mutationState);mutationState=after;const changed=enforceMutation?mutationDiff(before,after):[];const forbidden=changed.filter(rel=>!allowedPath(rel,v.mutates_files||[]));if(forbidden.length)fs.appendFileSync(logFile,`\nFORBIDDEN SOURCE MUTATIONS\n${forbidden.join('\n')}\n`);const timedOut=Boolean(r.error&&r.error.code==='ETIMEDOUT');const nonzero=timedOut||r.status!==0||forbidden.length>0;const combined=`${r.stdout||''}\n${r.stderr||''}`;const warningFound=detectWarning(v,combined);const missingOutputs=(v.produces_files||[]).filter(rel=>!exists(rel));const effectiveNonzero=nonzero||missingOutputs.length>0;const policy=classifyResult({severity:v.severity,nonzero:effectiveNonzero,warningFound,timedOut,strictWarnings:args.strictWarnings});if(policy.blocks){blocked=true;console.error(`BLOCKING RESULT: ${v.id} => ${policy.status}`);}else console.log(`RESULT: ${v.id} => ${policy.status}`);results.push({id:v.id,title:v.title,status:policy.status,severity:v.severity,scope:v.scope,tier:v.tier,depends_on:v.depends_on||[],exit_code:r.status,signal:r.signal||null,timed_out:timedOut,duration_ms:Date.now()-started,warning_detected:warningFound,blocks_release:policy.blocks,missing_outputs:missingOutputs,source_mutations:changed,forbidden_source_mutations:forbidden,prepare_results:prepareResults,evidence_file:v.evidence_file||null,log:path.relative(ROOT,logFile).replace(/\\/g,'/')});}
 const counts={};for(const r of results)counts[r.status]=(counts[r.status]||0)+1;const report={schema_version:'3.0',generated_at:stableTimestamp(),profiles:args.profiles,validator_ids:validators.map(v=>v.id),execution_order:validators.map(v=>v.id),profile_validator_ids:profileValidatorIds,shard:shard?{index:shard.index,count:shard.count,assigned_ids:shard.assigned_ids,weights_source:shard.weights_source,assigned_weight_ms:shard.assigned_weight_ms,loads_ms:shard.loads_ms}:null,collect_all:args.collectAll,strict_warnings:args.strictWarnings,include_local:args.includeLocal,status:blocked?'FAIL':'PASS',counts,results};fs.mkdirSync(path.join(ROOT,'artifacts/validation'),{recursive:true});if(shard){fs.writeFileSync(path.join(ROOT,`artifacts/validation/validation-summary-shard-${shard.index}-of-${shard.count}.json`),JSON.stringify(report,null,2)+'\n');console.log(`\nVALIDATION SUMMARY (shard ${shard.index}/${shard.count}): ${report.status} ${JSON.stringify(counts)}`);if(blocked){emitFailureLegibility(report,{root:ROOT});process.exit(1);}return;}fs.writeFileSync(path.join(ROOT,'artifacts/validation/validation-summary.json'),JSON.stringify(report,null,2)+'\n');let key=(args.profiles.length?args.profiles.join('-'):(args.ids.length?'ids-'+args.ids.join('-'):'core')).replace(/[^a-z0-9-]+/gi,'-').toLowerCase();if(key.length>120){const crypto=require('crypto');key=key.slice(0,80)+'-'+crypto.createHash('sha256').update(key).digest('hex').slice(0,16);}fs.writeFileSync(path.join(ROOT,`artifacts/validation/validation-summary-${key}.json`),JSON.stringify(report,null,2)+'\n');console.log(`\nVALIDATION SUMMARY: ${report.status} ${JSON.stringify(counts)}`);if(blocked){emitFailureLegibility(report,{root:ROOT});process.exit(1);}}
try{main();}catch(err){console.error(`VALIDATION RUNNER ERROR: ${err.stack||err.message}`);process.exit(1);}
