#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'); const ROOT=path.resolve(__dirname,'..','..'); const read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8')); const errors=[];
const identity=read('data/network/network_identity_registry.json'); const policy=read('data/network/crawler_policy.json'); const robots=fs.readFileSync(path.join(ROOT,'robots.txt'),'utf8'); const admission=read('data/content/page_admission_registry.json');
for(const agent of ['Googlebot','Bingbot','OAI-SearchBot','GPTBot','ChatGPT-User','ClaudeBot','PerplexityBot','Google-Extended']){if(!(policy.agents||[]).some(a=>a.agent===agent&&a.directive==='Allow'))errors.push(`policy_missing:${agent}`);if(!robots.includes(`User-agent: ${agent}`))errors.push(`robots_missing:${agent}`)}
const hasSameAs=(v)=>Array.isArray(v)?v.some(hasSameAs):(v&&typeof v==='object'?Object.entries(v).some(([k,x])=>k==='sameAs'||hasSameAs(x)):false);if(hasSameAs(identity.organization)||hasSameAs(identity.website))errors.push('unsupported_sameAs_present');
function fileFor(route){if(route==='/')return path.join(ROOT,'index.html');if(route.endsWith('.html'))return path.join(ROOT,route.replace(/^\//,''));return path.join(ROOT,route.replace(/^\//,'').replace(/\/$/,''),'index.html')}
let checked=0; for(const p of admission.pages||[]){const file=fileFor(p.path);if(!fs.existsSync(file)){errors.push(`missing_render:${p.path}`);continue}checked++;const html=fs.readFileSync(file,'utf8');for(const id of ['https://theindustryguides.com/#organization','https://theindustryguides.com/#website'])if(!html.includes(id))errors.push(`rendered_schema_missing:${p.path}:${id}`)}
const report={validator:'network-crawler-contract',ok:!errors.length,agents:(policy.agents||[]).length,routes_checked:checked,errors};fs.mkdirSync(path.join(ROOT,'artifacts','validation'),{recursive:true});fs.writeFileSync(path.join(ROOT,'artifacts','validation','network-crawler-contract.json'),JSON.stringify(report,null,2)+'\n');if(errors.length){console.error(errors.slice(0,60).join('\n'));process.exit(1)}console.log(`Network identity and explicit crawler contract passed for ${checked} rendered routes.`);
