#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'../..');const errors=[];const read=r=>JSON.parse(fs.readFileSync(path.join(ROOT,r),'utf8'));const check=(c,m)=>{if(!c)errors.push(m);};
const rec=read('data/citation_velocity/recommendations.json'),runs=read('data/citation_velocity/runs.json'),wins=read('data/citation_velocity/wins.json');const accept=read('data/citation_velocity/page_acceptance_registry.json'),own=read('data/citation_velocity/source_ownership_registry.json'),admission=read('data/content/page_admission_registry.json'),published=read('content/_live/published_urls.json'),specs=read('data/page_families/velocity_page_specs.json'),scopeContract=read('data/overhaul/full_scope_overhaul_contract.json');
const monitorPath=path.join(ROOT,'artifacts/validation/monitor-ledger.json');if(!fs.existsSync(monitorPath))errors.push('monitor-ledger:evidence-missing');else{const m=JSON.parse(fs.readFileSync(monitorPath,'utf8'));check(m.status==='PASS','monitor-ledger:not-pass');}
const recs=rec.recommendations||[],runRows=runs.runs||[],winRows=wins.wins||[];
check(own.count===own.records.length,'ownership:self-count');check(own.records.length===recs.length,'ownership:recommendation-parity');check(new Set(own.records.map(x=>x.recommendation_id)).size===own.records.length,'ownership:duplicate-or-missing');
for(const r of recs){check(r.source_owner==='VELOCITY_CONTENT',`recommendation:owner:${r.id}`);check(['IMPLEMENTED','PRESERVED'].includes(r.implementation_status),`recommendation:status:${r.id}`);check(Array.isArray(r.source_paths)&&r.source_paths.length>0,`recommendation:source:${r.id}`);}
check(accept.count===accept.pages.length,'acceptance:self-count');for(const p of accept.pages||[]){check(p.source_owners?.length===1&&p.source_owners[0]==='VELOCITY_CONTENT',`acceptance:owner:${p.id}`);check(['IMPLEMENTED','PRESERVED'].includes(p.implementation_status),`acceptance:status:${p.id}`);}
const june=runRows.find(r=>r.id==='CV-RUN-USCIS-MEDICAL-2026-06-19');check(Boolean(june),'fixture:uscis-2026-06-19-run');if(june){check(june.queries===30,'fixture:uscis-queries');check(june.levels?.L1===30&&june.levels?.L2===0&&june.levels?.L3===0&&june.levels?.L4===0,'fixture:uscis-levels');}
for(const [id,page] of [['CV-USCIS-018','/uscis-medical/'],['CV-USCIS-019','/uscis-medical/correction-mistakes/'],['CV-USCIS-020','/uscis-medical/timeline-validity/']]){const row=recs.find(r=>r.id===id);check(Boolean(row),`fixture:missing:${id}`);if(row)check(row.page===page,`fixture:page:${id}`);}
const minVelocitySpecs=Number(scopeContract.minimums?.velocity_state_and_support_pages||scopeContract.counts?.velocity_state_and_support_pages||0);check(specs.pages.length===specs.count,'velocity-specs:self-count');check(specs.pages.length>=minVelocitySpecs,`velocity-specs:below-minimum:${specs.pages.length}<${minVelocitySpecs}`);check(admission.count===admission.pages.length&&admission.count===published.items.length,'admission:dynamic-parity');check(new Set(admission.pages.map(p=>p.path)).size===admission.pages.length,'admission:duplicate-path');const admitted=new Set(admission.pages.filter(p=>p.publication_status==='ADMITTED').map(p=>p.path));for(const item of published.items)check(admitted.has(item.path),`admission:missing:${item.path}`);for(const spec of specs.pages){const route=spec.path||spec.slug;check(admitted.has(route),`velocity-route:not-admitted:${route}`);}
for(const rel of ['data/canonical_candidates','data/lkg_candidates','.github/workflows/lkg_pr_push.yml','scripts/export_promotion_candidates.js','scripts/community/export_lkg_candidates.js'])check(!fs.existsSync(path.join(ROOT,rel)),`forbidden-external-handoff:${rel}`);
const report={validator:'citation-velocity-master-plan',status:errors.length?'FAIL':'PASS',ok:!errors.length,counts:{recommendations:recs.length,runs:runRows.length,wins:winRows.length,acceptance_pages:accept.pages.length,admitted_routes:admission.pages.length,velocity_routes:specs.pages.length},count_policy:'DERIVED_FROM_LEDGER',historical_fixture:'USCIS_2026_06_19',errors,checked_at:runs.current_through};fs.mkdirSync(path.join(ROOT,'artifacts/validation'),{recursive:true});fs.writeFileSync(path.join(ROOT,'artifacts/validation/citation-velocity.json'),JSON.stringify(report,null,2)+'\n');if(errors.length){console.error(errors.slice(0,200).join('\n'));process.exit(1);}console.log(`CITATION VELOCITY PASS (${recs.length} recommendations, ${runRows.length} runs, ${winRows.length} wins; counts derived, June 19 fixture immutable)`);
