#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'../..');const read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));const errors=[];const eq=(a,b,l)=>{if(a!==b)errors.push(`${l}:${a}!=${b}`)};
const contract=read('data/overhaul/full_scope_overhaul_contract.json'),minimums=contract.minimums||{},retirements=read('data/release/route_retirements.json'),staged=read('content/_staged/pages.json'),live=read('content/_live/pages.json'),specs=read('data/page_families/velocity_page_specs.json'),admission=read('data/content/page_admission_registry.json'),published=read('content/_live/published_urls.json'),runs=read('data/citation_velocity/runs.json');
const minSpecs=Number(minimums.velocity_state_and_support_pages||contract.counts.velocity_state_and_support_pages||0);if(specs.pages.length<minSpecs)errors.push(`velocity_specs_below_minimum:${specs.pages.length}<${minSpecs}`);
for(const [name,p] of [['staged',staged],['live',live]]){const dis=(p.pages||[]).filter(x=>x.full_scope_program==='VELOCITY_DISAMBIGUATOR_20').length;const qs=(p.pages||[]).filter(x=>x.full_scope_program==='VELOCITY_QUESTION_200').length;const minDis=Number(minimums.velocity_disambiguators||contract.counts.velocity_disambiguators||0);const minQs=Number(minimums.velocity_questions||contract.counts.velocity_questions||0);if(dis<minDis)errors.push(`${name}_disambiguators_below_minimum:${dis}<${minDis}`);if(qs<minQs)errors.push(`${name}_questions_below_minimum:${qs}<${minQs}`);}
eq(admission.count,admission.pages.length,'admission_self_count');eq(admission.count,published.items.length,'admission_publish_parity');const activeRetirements=(retirements.retirements||[]).filter(r=>r.status==='ACTIVE_301').length;eq(activeRetirements,Number(contract.counts.approved_route_retirements||0),'approved_route_retirements');const effectiveInventory=admission.count+activeRetirements;const historicalBaseline=Number(contract.counts.historical_admitted_routes_baseline||0);if(admission.count<Number(contract.counts.minimum_active_admitted_routes||0))errors.push(`active_admission_below_minimum:${admission.count}`);if(effectiveInventory<historicalBaseline)errors.push(`unexplained_inventory_regression:${effectiveInventory}<${historicalBaseline}`);
if(!(runs.runs||[]).some(r=>r.id==='CV-RUN-USCIS-MEDICAL-2026-06-19'))errors.push('missing_june19_uscis_fixture');for(const p of ['data/canonical_candidates','data/lkg_candidates','.github/workflows/lkg_pr_push.yml'])if(fs.existsSync(path.join(ROOT,p)))errors.push(`forbidden:${p}`);
const report={validator:'full-scope-overhaul',ok:!errors.length,errors,counts:{admission:admission.count,approved_retirements:activeRetirements,effective_inventory:effectiveInventory,velocity_specs:specs.pages.length,historical_baseline:historicalBaseline,minimum_velocity_specs:minSpecs}};fs.mkdirSync(path.join(ROOT,'artifacts/validation'),{recursive:true});fs.writeFileSync(path.join(ROOT,'artifacts/validation/full-scope-overhaul.json'),JSON.stringify(report,null,2)+'\n');if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log(`Velocity-only full-scope overhaul PASS (${admission.count} admitted routes; approved-retirement-adjusted baseline preserved)`);
