#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');const ROOT=path.resolve(__dirname,'../..');const read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));const errors=[];const eq=(a,b,l)=>{if(a!==b)errors.push(`${l}:${a}!=${b}`)};
const contract=read('data/overhaul/full_scope_overhaul_contract.json'),staged=read('content/_staged/pages.json'),live=read('content/_live/pages.json'),specs=read('data/page_families/velocity_page_specs.json'),admission=read('data/content/page_admission_registry.json'),published=read('content/_live/published_urls.json'),runs=read('data/citation_velocity/runs.json');
eq(contract.counts.velocity_state_and_support_pages,412,'contract_velocity_pages');eq(specs.pages.length,412,'velocity_specs');
for(const [name,p] of [['staged',staged],['live',live]]){eq((p.pages||[]).filter(x=>x.full_scope_program==='VELOCITY_DISAMBIGUATOR_20').length,20,`${name}_disambiguators`);eq((p.pages||[]).filter(x=>x.full_scope_program==='VELOCITY_QUESTION_200').length,200,`${name}_questions`);}
eq(admission.count,admission.pages.length,'admission_self_count');eq(admission.count,published.items.length,'admission_publish_parity');if(admission.count<Number(contract.counts.admitted_routes_target||1763))errors.push(`admission_below_locked_baseline:${admission.count}`);
if(!(runs.runs||[]).some(r=>r.id==='CV-RUN-USCIS-MEDICAL-2026-06-19'))errors.push('missing_june19_uscis_fixture');for(const p of ['data/canonical_candidates','data/lkg_candidates','.github/workflows/lkg_pr_push.yml'])if(fs.existsSync(path.join(ROOT,p)))errors.push(`forbidden:${p}`);
const report={validator:'full-scope-overhaul',ok:!errors.length,errors,counts:{admission:admission.count,velocity_specs:specs.pages.length,locked_baseline:Number(contract.counts.admitted_routes_target||1763)}};fs.mkdirSync(path.join(ROOT,'artifacts/validation'),{recursive:true});fs.writeFileSync(path.join(ROOT,'artifacts/validation/full-scope-overhaul.json'),JSON.stringify(report,null,2)+'\n');if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log(`Velocity-only full-scope overhaul PASS (${admission.count} admitted routes; baseline floor preserved)`);
