#!/usr/bin/env node
'use strict';
const fs=require('fs');const path=require('path');const L=require('../search_intelligence/lib');const errors=[];const warnings=[];
const baseline=L.readJson('data/search_intelligence/protected_agent_tree_manifest.json');const now=L.protectedAgentSnapshot();
const baselinePaths=new Set((baseline.files||[]).map(x=>x.path));const additions=now.filter(x=>!baselinePaths.has(x.path));
const bridge=L.readJson('data/search_intelligence/agent_signal_bridge.json',{signals:[]});if(bridge.source_mode!=='READ_ONLY_AGENT_OUTPUTS')errors.push('bridge_source_mode_not_read_only');if(bridge.mutation_authority!==false)errors.push('bridge_mutation_authority_not_false');if((bridge.signals||[]).some(s=>s.read_only!==true))errors.push('bridge_signal_not_read_only');
try{L.assertProtectedAgentSnapshotUnchanged(now,now);}catch(e){errors.push(`runtime_guard_unusable:${e.message}`);}
const searchSource=fs.readFileSync(path.join(L.ROOT,'scripts/search_intelligence/search_intelligence.js'),'utf8');if(!searchSource.includes('protectedAgentSnapshot()')||!searchSource.includes('assertProtectedAgentSnapshotUnchanged'))errors.push('runtime_full_lane_guard_missing');
if(additions.length)warnings.push(`post_baseline_agent_artifacts_present:${additions.length}`);
const report={validator:'search-intelligence-agent-separation',status:errors.length?'FAIL':'PASS',historical_manifest_role:'REFERENCE_ONLY_NOT_RUNTIME_AUTHORITY',historical_baseline_file_count:(baseline.files||[]).length,current_protected_file_count:now.length,post_baseline_addition_count:additions.length,aggregate_sha256:L.aggregateManifest(now),runtime_guard:'BEFORE_AFTER_CURRENT_TREE',separation_authority:'SEARCH_INTELLIGENCE_RUNTIME_BEFORE_AFTER_GUARD',artifact_validity_authority:'AGENT_PROVENANCE_CONTINUITY_AND_VELOCITY_INTAKE_VALIDATORS',new_artifact_policy:'ALLOWED_IF_PRESENT_BEFORE_SEARCH_INTELLIGENCE;ANY ADD_CHANGE_DELETE DURING SEARCH INTELLIGENCE HARD_FAILS',errors,warnings};L.writeJson('artifacts/validation/search-intelligence-agent-separation.json',report);if(errors.length){console.error(errors.join('\n'));process.exit(1);}console.log(`SEARCH INTELLIGENCE AGENT SEPARATION PASS: current=${now.length} post_baseline=${additions.length} runtime_guard=ON historical_manifest=REFERENCE_ONLY`);
