#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'); const ROOT=path.resolve(__dirname,'../..'); const dir=path.join(ROOT,'.github/workflows'); const files=fs.readdirSync(dir).filter(f=>/\.ya?ml$/.test(f)); const errors=[],fingerprints=[];
for(const f of files){const text=fs.readFileSync(path.join(dir,f),'utf8');fingerprints.push({file:f,sha256:crypto.createHash('sha256').update(text).digest('hex')});if(/actions\/checkout@(?!v4)/.test(text))errors.push(`${f}:checkout-version`);if(/actions\/setup-node@(?!v4)/.test(text))errors.push(`${f}:setup-node-version`);const versions=[...text.matchAll(/node-version:\s*["']?([^"'\s#]+)/g)].map(m=>m[1]);if(!versions.length||versions.some(v=>!/^24(?:\.|$)/.test(v)))errors.push(`${f}:node-version`);if(/create-pull-request|LKG_REPO|LKG_TOKEN|lkg:candidates/i.test(text))errors.push(`${f}:cross-repo-lkg-surface`);}
for(const required of ['validate.yml','velocity_content_release.yml','velocity_full_rebuild.yml','deploy-distribution.yml','postdeploy_public_audit.yml'])if(!files.includes(required))errors.push(`missing:${required}`);
const content=fs.readFileSync(path.join(dir,'velocity_content_release.yml'),'utf8');if(!/release:velocity-content/.test(content)||!/git push origin HEAD:main/.test(content))errors.push('velocity_content_release:not-autonomous');
const validate=fs.readFileSync(path.join(dir,'validate.yml'),'utf8');if(!/release:ci-validate/.test(validate))errors.push('validate.yml:central-command');
const dist=fs.readFileSync(path.join(dir,'deploy-distribution.yml'),'utf8');if(/npm run build|distribution:prepare/.test(dist))errors.push('deploy-distribution:must-not-rebuild');if(!/download-artifact@v4/.test(dist))errors.push('deploy-distribution:download-validated-artifact');
const report={validator:'workflow-contract',ok:!errors.length,errors,fingerprints};fs.mkdirSync(path.join(ROOT,'artifacts/validation'),{recursive:true});fs.writeFileSync(path.join(ROOT,'artifacts/validation/workflow.json'),JSON.stringify(report,null,2)+'\n');if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log('VELOCITY WORKFLOW CONTRACT PASS');
