#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'); const ROOT=path.resolve(__dirname,'../..'); const required=['REPO_IDENTITY.md','_repo_update_contract.json','_repo_lifecycle_profile.json','_repo_validation_matrix.json','_validation_registry.json','_browser_suite_contract.json','_public_route_manifest.json','_baseline_packaging_contract.json','data/citation_velocity/recommendations.json','data/citation_velocity/runs.json','data/citation_velocity/wins.json','data/citation_velocity/page_acceptance_registry.json','data/citation_velocity/source_ownership_registry.json','data/content/page_admission_registry.json','data/page_families/velocity_page_specs.json','docs/ARCHITECTURAL_DECISIONS.md','docs/architecture/ADR-2026-06-19-02-VELOCITY-ONLY.md','docs/overhaul/VELOCITY_ONLY_FULL_SCOPE_OVERHAUL.md','scripts/validation/run_validation_registry.js','scripts/validators/validate_velocity_only_overhaul.js']; const errors=[];
for(const rel of required)if(!fs.existsSync(path.join(ROOT,rel)))errors.push(`missing:${rel}`);
if(!errors.length){const identity=fs.readFileSync(path.join(ROOT,'REPO_IDENTITY.md'),'utf8');if(!/Velocity-only/i.test(identity))errors.push('identity:velocity-only-missing');if(/canonical candidate|export LKG|LKG canonical/i.test(identity))errors.push('identity:obsolete-cross-repo-language');const life=JSON.parse(fs.readFileSync(path.join(ROOT,'_repo_lifecycle_profile.json'),'utf8'));if(life.node_version!=='24')errors.push('lifecycle:node-24-required');if(life.validation_is_pure!==true)errors.push('lifecycle:validate-all-must-be-pure');if(life.cross_repo_pull_requests!==false)errors.push('lifecycle:cross-repo-pr-not-disabled');const pkg=JSON.parse(fs.readFileSync(path.join(ROOT,'package.json'),'utf8'));for(const name of ['build','validate:all','release:prepush','release:ci-validate','release:velocity-content','release:full-rebuild','postdeploy:public-click-audit'])if(!pkg.scripts?.[name])errors.push(`package:missing-script:${name}`);for(const name of Object.keys(pkg.scripts||{}))if(/^lkg:|export:promotion|validate:lkg/.test(name))errors.push(`package:forbidden-script:${name}`);}
const packaging=JSON.parse(fs.readFileSync(path.join(ROOT,'_baseline_packaging_contract.json'),'utf8'));
for(const forbidden of ['data/canonical_candidates/full_scope_2026_06_19/manifest.json','data/lkg_candidates/latest.json']) if((packaging.required||[]).includes(forbidden))errors.push(`packaging:forbidden-required:${forbidden}`);
for(const needed of ['data/page_families/velocity_page_specs.json','artifacts/release/VELOCITY_ONLY_MASTER_PLAN_COMPLETION_CHECKLIST.md','artifacts/release/validation-attestation.json']) if(!(packaging.required||[]).includes(needed))errors.push(`packaging:missing-required:${needed}`);
const report={validator:'authority-contracts',ok:!errors.length,errors};fs.mkdirSync(path.join(ROOT,'artifacts/validation'),{recursive:true});fs.writeFileSync(path.join(ROOT,'artifacts/validation/authority-contracts.json'),JSON.stringify(report,null,2)+'\n');if(errors.length){console.error(errors.join('\n'));process.exit(1)}console.log('VELOCITY AUTHORITY CONTRACTS PASS');
