name: Validate Repo

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Run audit
        run: npm run audit:all

      - name: Run validation
        run: npm run validate:all
